client/src/features/editors/Editor.jsx, client/src/features/menu/MenuBar.jsx, client/src/features/menu/buttons/SettingsIconBtn.jsx, client/src/features/modals/ModalManager.jsx, client/src/features/modals/SettingsModal.jsx
- Create a modal with tabs for reusability
=> modal manager

server/src/classes/Timer.js
fix issue where time from midnight was wrong on days where DST changes
=> fix: time from midnight

client/src/features/editors/Editor.module.css, client/src/features/viewers/backstage/StageManager.jsx, server/main.js
=> Fixed issues with style on small windows

client/package.json, client/src/features/table/tableElements/EditableCell.jsx, server/package.json
fixes an issue with the textarea element not re-rendering on receiving new data
=> fix(203): issue with userfields re-rendering

client/package.json, client/src/features/modals/OscSettingsModal.jsx, client/src/features/modals/modalHelper.js, server/package.json
Adds a small fix to revert a change in the modal inputs.
Change is likely from the UI library
=> style: revert input style

client/package.json, client/src/features/table/TableHeader.jsx, client/src/features/table/tableElements/EditableCell.jsx, server/package.json
We use the Chakra UI TextArea component in the table views.
It seems that somewhere along the line the text colour was no longer responding to the page background
=> Fix: issue with text colour

client/package.json, client/src/features/viewers/minimal-timer/MinimalTimer.tsx, server/package.json
fixes issues with inline css in <MinimalTimer>
=> fix: issue with css override

client/package.json, server/package.json, server/src/controllers/OscController.js, server/src/package.json
adds workflow for OSC feedback endpoints
=> feat: OSC feedback

client/package.json, server/package.json, server/src/package.json, server/src/utils/__tests__/parser.tests.js, server/src/utils/parser.js
revises logic around empty strings on excel import
=> refactor: excel import

client/package.json, client/src/features/table/utils.js, client/yarn.lock, server/package.json
Leverage library to handle edge cases on CSV export
=> fix(csv-export): escape special characters

client/src/common/api/eventsApi.ts, client/src/common/components/input/colour-input/ColourInput.tsx, client/src/common/components/state/Empty.tsx, client/src/common/hooks-query/useAliases.ts, client/src/common/hooks-query/useEvent.ts, client/src/common/hooks-query/useInfo.ts, client/src/common/hooks-query/useOscSettings.ts, client/src/common/hooks-query/useRundown.ts, client/src/common/hooks-query/useSettings.ts, client/src/common/hooks-query/useUserFields.ts, client/src/common/hooks-query/useViewSettings.ts, client/src/common/hooks/useEventAction.ts, client/src/common/hooks/useFullscreen.js, client/src/common/hooks/useSocket.ts, client/src/common/models/EventTypes.ts, client/src/features/control/playback/Transport.tsx, client/src/features/event-editor/EventEditor.tsx, client/src/features/modals/AppSettingsModal.jsx, client/src/features/modals/ViewsSettingsModal.jsx, client/src/features/rundown/Rundown.tsx, client/src/features/rundown/RundownEntry.tsx, client/src/features/rundown/event-block/EventBlock.module.scss, client/src/features/rundown/event-block/EventBlock.tsx, client/src/features/rundown/event-block/composite/BlockActionMenu.tsx, client/src/features/rundown/quick-add-block/QuickAddBlock.tsx, client/src/ontimeConfig.ts, client/src/theme/_v2Styles.scss, client/src/theme/ontimeMenu.ts, client/vite.config.js, server/src/services/rundownService.js
Fixing feedback related to 3rd round of alpha testing:
- issues with DnD and re-ordering
- add polling to REST endpoints
- small style and UX cleanups
=> v2 alpha 3

apps/client/src/features/viewers/ViewWrapper.jsx
fix reading wrong parameter in viewWrapper
=> fix: wrong parameter

apps/client/src/App.tsx, apps/client/src/AppRouter.tsx, apps/client/src/common/models/View.types.ts, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/public/Public.tsx, apps/client/src/features/viewers/timer/Timer.tsx, apps/client/src/translation/Translation.types.ts, apps/client/src/translation/TranslationProvider.jsx, apps/client/src/translation/languages/de.ts, apps/client/src/translation/languages/en.ts, pnpm-lock.yaml
=> Add translations for views

apps/client/src/App.tsx, apps/client/src/AppRouter.tsx, apps/client/src/common/components/title-card/TitleCard.tsx, apps/client/src/common/models/View.types.ts, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/countdown/Countdown.tsx, apps/client/src/features/viewers/countdown/CountdownSelect.tsx, apps/client/src/features/viewers/countdown/countdown.helpers.ts, apps/client/src/features/viewers/public/Public.tsx, apps/client/src/features/viewers/timer/Timer.tsx, apps/client/src/translation/Translation.types.ts, apps/client/src/translation/TranslationProvider.jsx, apps/client/src/translation/languages/de.ts, apps/client/src/translation/languages/en.ts
Adds localised strings for 
* Add foundation for views translation
* WIP: Move hard-coded strings to translation map
* Add foundation for views translation
* WIP: Translations
* Use flat Javascript object for translation mappings
* Revert lock file back to original state
* Rename getString() to getLocalizedString()
=> Add translations for views (#325)

apps/client/src/common/utils/__tests__/eventsManager.test.js, apps/client/src/common/utils/eventsManager.ts, apps/client/src/common/utils/time.ts
fixes issue with delay calculating mutating original array
=> V2 fix delay

apps/client/package.json, apps/client/vite.config.js, apps/server/package.json, apps/server/src/app.ts, pnpm-lock.yaml
Configure compression of react app at build time. 
This has reduced the time to FCP by half
=> refactor: serve react as compressed br

apps/client/src/common/utils/__tests__/dateConfig.test.js, apps/client/src/common/utils/dateConfig.ts
Allows shorthands for am / pm keywords in time input
=> feat: 12 hour time input

apps/client/src/common/hooks/useSocket.ts, apps/client/src/features/control/playback/PlaybackControl.tsx, apps/client/src/features/control/playback/playback-buttons/PlaybackButtons.tsx
small UX improvements in the playback buttons to make them content aware
=> ux: content aware playback

README.md, apps/client/package.json, apps/electron/package.json, apps/server/package.json, package.json
=> v2 beta 4 bump

apps/client/src/AppRouter.tsx, apps/client/src/features/modals/settings-modal/AppSettings.tsx, apps/client/src/features/viewers/ViewWrapper.tsx, apps/client/src/translation/TranslationProvider.jsx, apps/client/src/translation/languages/de.ts, apps/client/src/translation/languages/es.ts, apps/client/src/translation/languages/pt.ts
improves workflow for changing viewer language
=> Ux language

.github/workflows/build_docker_v2.yml, apps/server/src/controllers/ontimeController.ts
Change the docker Publish action from V2 to latest
=> Docker latest

apps/server/src/controllers/ontimeController.ts, apps/server/src/services/RundownService.ts
Fixes issue where uploading a database left stale data in the runtime store
=> fix: reset rundown on upload

apps/server/src/utils/__tests__/parser.test.js, apps/server/src/utils/parser.ts, apps/server/src/utils/parserFunctions.ts
Introduced reading the `End Action` and `Timer Type` on the Excel file used for import
=> add endAction and timerType validation to excel upload

apps/client/src/App.tsx, apps/client/src/common/context/ContextMenuContext.module.scss, apps/client/src/common/context/ContextMenuContext.tsx, apps/client/src/common/hooks/useContextMenu.tsx, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/rundown/event-block/EventBlock.tsx
closes #389 
- create `ContextMenuProvider` component responsible for determining look, state, position, and options of context menu. 
- wrap `App.tsx` with `ContextMenuProvider` 
- create `useContextMenu` hook to access said context. It receives an `Option[]` arg and returns an event handler that should be passed to a `onContextMenu`. (However, the returned event handler can be used for any of the element's event callbacks, but perhaps this flexibility is welcome.)
The above implementation does have an issue with positioning. I spent a few hours trying to pinpoint this bug, but I believe it comes down to how the elements on the page are positioned. I'd love some help with this!
https://github.com/cpvalente/ontime/assets/58940073/fce9cecf-5cad-4dcb-9dab-963df8285673
Happy to discuss …
=> Context Menu Feature

apps/client/src/common/components/timer-display/TimerDisplay.scss, apps/client/src/features/control/playback/playback-buttons/PlaybackButtons.module.scss, apps/client/src/features/control/playback/playback-timer/PlaybackTimer.module.scss, apps/client/src/features/control/playback/tap-button/TapButton.module.scss, apps/client/src/features/editors/Editor.module.scss, apps/client/src/features/event-editor/EventEditor.module.scss, apps/client/src/features/event-editor/EventEditor.tsx, apps/client/src/features/info/Info.module.scss, apps/client/src/features/info/Info.tsx, apps/client/src/features/menu/MenuBar.tsx, apps/client/src/features/modals/settings-modal/SettingsModal.tsx, apps/client/src/features/rundown/_blockMixins.scss, apps/client/src/features/rundown/common/TitleEditor.module.scss, apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/index.scss, apps/client/src/theme/_mixins.scss, apps/client/src/theme/_v2Styles.scss, apps/server/src/controllers/ontimeController.ts, apps/server/src/services/RundownService.ts
small tweaks to make the views happy in macOS.
Closes #359
=> style v2 tweaks

apps/client/src/common/components/copy-tag/CopyTag.tsx, apps/client/src/common/utils/copyToClipboard.ts, apps/client/src/features/rundown/event-block/EventBlock.tsx
Adds simple actions to the <EventBlock> context menu
=> feat: context menu actions

apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/timer/Timer.tsx
fixes small issue with progress bar not accounting for added time
=> fix: progress bar handles added time

apps/client/package.json, apps/client/src/common/components/buttons/TooltipActionBtn.tsx, apps/client/src/common/components/edit-form-drawer/EditFormInput.tsx, apps/client/src/common/components/error-boundary/ErrorBoundary.jsx, apps/client/src/common/components/input/time-input/TimeInput.tsx, apps/client/src/common/hooks/useKeyDown.ts, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/event-editor/composite/CountedTextArea.tsx, apps/client/src/features/event-editor/composite/CountedTextInput.tsx, apps/client/src/features/event-editor/composite/EventEditorTimes.tsx, apps/client/src/features/rundown/RundownWrapper.tsx, apps/client/src/index.tsx, apps/client/src/theme/ontimeSwitch.ts, apps/electron/package.json, apps/server/package.json, apps/server/src/adapters/OscAdapter.ts, apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/services/integration-service/OscIntegration.ts, apps/server/src/utils/parserFunctions.ts, apps/server/src/utils/upload.js, package.json
small refactors and version bump for v2
=> v2 cleanup

apps/client/src/common/components/error-boundary/ErrorBoundary.jsx, apps/client/src/common/utils/socket.ts, apps/client/src/index.tsx
add some context on network status to sentry
also ignore some errors caused by 3rd party
=> chore: improve bug reporting data

apps/client/src/features/control/playback/playback-buttons/PlaybackButtons.tsx, apps/client/src/features/table/__tests__/utils.test.js
small clarification on types. partially resolved in #435 
changed icon to improve visibility of roll button
=> style: small tweaks on code style and editor UI

apps/client/src/features/operator/Operator.module.scss, apps/client/src/features/operator/Operator.tsx, apps/client/src/features/operator/op-block/OpBlock.module.scss, apps/client/src/features/operator/op-block/OpBlock.tsx, apps/client/src/features/operator/op-event/OpEvent.module.scss, apps/client/src/features/operator/op-event/OpEvent.tsx, apps/client/src/features/operator/time-block/TimeBlock.module.scss, apps/client/src/features/operator/time-block/TimeBlock.tsx, pnpm-lock.yaml
- Made OpBlock, OpEvent, TimeBlock components with scss files for each
- Added Styling from OnTime colors
- Added overflow scrolling
=> Make Operator Layout 

apps/client/src/features/control/playback/playback-buttons/PlaybackButtons.tsx, apps/client/src/theme/_v2Styles.scss, apps/server/src/services/PlaybackService.ts, apps/server/src/services/TimerService.ts, packages/utils/index.ts, packages/utils/package.json, packages/utils/src/validate-action/validatePlayback.ts, pnpm-lock.yaml
Adds the possibility to interchange between roll and other playback modes.
Closes #400
=> refactor: roll handover

apps/client/package.json, apps/electron/package.json, apps/server/package.json, apps/server/src/services/TimerService.ts, package.json, packages/utils/package.json
Found the issue described to be from a "Good optimisation"(™) introduced in #430 
closes #455
=> fix: issues with clock overflow on midnight

apps/client/src/App.tsx, apps/client/src/common/components/navigation-menu/NavigationMenu.tsx, apps/client/src/common/components/navigation-menu/rename-client-modal/RenameClientModal.module.scss, apps/client/src/common/components/navigation-menu/rename-client-modal/RenameClientModal.tsx, apps/client/src/common/hooks/useSocket.ts, apps/client/src/common/stores/connectionName.ts, apps/client/src/common/utils/socket.ts, apps/server/src/adapters/WebsocketAdapter.ts
Adds a simple interface for user to be able to rename the websocket client connection
=> feat: allow renaming connection

apps/client/index.html, apps/client/src/common/hooks/useFullscreen.ts
remove attempt with meta tag and bruteforce error catching
=> fix: prevent typerror on fullscreen request

apps/client/src/common/api/apiConstants.ts, apps/client/src/common/components/view-params-editor/ParamInput.tsx, apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/common/components/view-params-editor/types.ts, apps/client/src/features/menu/MenuBar.tsx, apps/client/src/features/viewers/backstage/Backstage.scss, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/translation/languages/de.ts, apps/client/src/translation/languages/en.ts, apps/client/src/translation/languages/es.ts, apps/client/src/translation/languages/no.ts, apps/client/src/translation/languages/pt.ts, apps/client/src/translation/languages/sv.ts, apps/server/src/external/styles/override.css
Pull some hotfixes from #460,
again, thank you @hrueger
=> many hotfixes

apps/client/src/features/info/Info.module.scss, apps/client/src/features/info/Info.tsx, apps/client/src/features/info/info-header/InfoHeader.tsx
Shows event name at the top of info panel as described in #358 
We will not, for now, add new production information to the event
Closes #358
=> style: show event title in info panel

apps/client/src/common/api/apiUtils.ts
small PR to handle the case where we get undefined in axios error
=> refactor: handle undefined

apps/server/package.json
PR solves issue with build:local failing to build the server
=> dx: improve local build command

apps/client/src/AppRouter.tsx, apps/client/src/common/utils/__tests__/aliases.test.js, apps/client/src/common/utils/aliases.ts, apps/client/src/common/utils/linkUtils.js, apps/client/src/features/AliasWrapper.tsx, apps/client/src/features/modals/settings-modal/AliasesForm.tsx
=> Adding Alias as a Parameter

apps/client/src/features/modals/settings-modal/AppSettings.tsx, apps/client/src/translation/TranslationProvider.tsx, apps/client/src/translation/languages/fr.ts, apps/client/src/translation/languages/sv.ts
Adds french language translations to the views. 
Thanks to Piotr Skotnicki
=> feat: add french translations

apps/server/src/services/TimerService.ts, apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/rundown-service/RundownService.ts, apps/server/src/services/rundown-service/delayedRundown.utils.ts, apps/server/src/services/timerUtils.ts
Prevent the timer from counting if we are paused.
This was visible in the cases of a timer which is counting up
=> fix paused

.github/workflows/build_v2.yml, apps/client/package.json, apps/electron/package.json, apps/server/package.json, package.json, packages/utils/package.json
Fixes typo in CI that prevents mac artifacts from being uploaded
=> fix: typo in macos release

apps/server/src/services/rundown-service/delayedRundown.utils.ts, e2e/tests/features/203-delay-block.spec.ts, packages/types/src/utils/guards.ts
fixes some bugs founds after #494
=> release test fixes

apps/client/src/features/rundown/block-block/BlockBlock.module.scss, apps/client/src/features/rundown/block-block/BlockBlock.tsx, apps/client/src/features/rundown/delay-block/DelayBlock.module.scss, apps/client/src/features/rundown/delay-block/DelayBlock.tsx, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/rundown/event-block/composite/BlockActionMenu.tsx, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.tsx, e2e/tests/features/204-editor-crud.spec.ts, packages/types/src/utils/guards.ts, packages/utils/src/cue-utils/cueUtils.test.ts, packages/utils/src/cue-utils/cueUtils.ts
Fixes issue introduced with cue feature where we expected the previous event to always contain a cue parameter
It also adds e2e tests for basic CRUD operations in the editor
=> fix: add event

apps/client/package.json, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.tsx, apps/client/src/index.tsx, apps/electron/package.json, apps/server/package.json, e2e/tests/features/204-editor-crud.spec.ts, package.json
This PR adds some config ahead of the next release
It is still missing the version bumps which are to come once we have locked in the features for the next release
=> chore: reduce sentry error logging

apps/client/src/common/utils/deviceUtils.ts, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.tsx
=> style: localise labels to user device

apps/client/src/features/modals/quick-start/QuickStart.tsx, apps/client/src/theme/OntimeAlert.ts, apps/client/src/theme/theme.ts
style change to warn users that submitting the quick start will clear their data 💀
=> style: warn quick start

apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/parser.ts
This PR adds sanitation to the imports to fix an existing bug with cue import from excel
=> fix: sanitise cue import

apps/client/src/common/hooks/useFullscreen.ts
small attempted fix to webkit fullscreen 🥶
=> refactor: prevent calling undefined

apps/client/src/common/hooks/useSocket.ts, apps/client/src/features/rundown/event-block/EventBlock.module.scss
Small tweaks from user feedback
=> style tweaks

apps/server/src/utils/parser.ts
small clarification on the naming of the import variables, useful ahead of work in excel import
=> refactor: clarify description import

.prettierignore, .prettierrc, apps/client/.prettierrc, apps/server/.prettierrc, packages/utils/.prettierrc
this PR adds line-end configuration in the prettier files.
It does not apply this, for now, we can do it later when there arent so many hanging PRs
=> chore: add line end to prettier

apps/server/src/controllers/ontimeController.ts
=> fix: prevent error when port is unchanged

apps/client/src/features/viewers/backstage/Backstage.scss
=> soft blink

apps/server/src/classes/event-loader/EventLoader.ts
Extracting the fix for the roll
=> fix: nullcheck for nextPublicEventId in findRoll

apps/client/src/common/utils/styleUtils.ts, apps/client/src/features/cuesheet/Cuesheet.module.scss, apps/client/src/features/cuesheet/cuesheet-table-elements/EventRow.tsx
Small improvements to the styling of the cuesheet
=> style: sticky index column

apps/server/package.json, apps/server/src/adapters/OscAdapter.ts, pnpm-lock.yaml
update node-osc to fix this issue https://github.com/MylesBorins/node-osc/issues/104
=> update node-osc to v9

apps/client/src/common/utils/styleUtils.ts, apps/client/src/features/cuesheet/Cuesheet.tsx
adding a little background colour to help with the labelling
=> style: coloured row background

apps/client/package.json, apps/client/src/features/cuesheet/CuesheetWrapper.tsx, apps/client/src/features/menu/MenuBar.tsx, apps/client/src/features/modals/export-modal/ExportModal.tsx, apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/features/viewers/backstage/Backstage.scss, apps/electron/package.json, apps/server/package.json, apps/server/src/controllers/integrationController.ts, package.json
Preparing release, is still missing version bump
Also
Closes #543
=> style: wording and UI tweaks

.github/workflows/build_docker_v2.yml, .github/workflows/build_v2.yml, .github/workflows/test_v2.yml, package.json, pnpm-lock.yaml
This upgrades pnpm, developers will have to upgrade locally too
=> chore: upgrade pnpm

apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx
closes #503 
- add local storage to persist saved views
=> View Params Persist when Navigating Back

.github/workflows/close_stale.yml
Workflow to close stale issues
=> ci: close issues without user activity

apps/client/src/common/components/schedule/ScheduleContext.tsx, apps/client/src/common/components/view-params-editor/constants.ts
=> add eventsPerPage to schedule

apps/client/src/common/api/apiUtils.ts, apps/client/src/common/hooks/useEventAction.ts, apps/server/src/classes/data-provider/DataProvider.ts, apps/server/src/controllers/ontimeController.ts, apps/server/src/controllers/playbackController.ts, apps/server/src/controllers/projectController.ts, apps/server/src/controllers/rundownController.ts, apps/server/src/modules/loadDb.ts, apps/server/src/services/rundown-service/RundownService.ts
Small PR to add consistency to error messages from backend
=> refactor: better errors

apps/client/src/features/modals/export-modal/ExportModal.module.scss, apps/client/src/features/modals/export-modal/ExportModal.tsx
=> style: export modal

apps/client/src/common/api/ontimeApi.ts, apps/client/src/common/hooks-query/useInfo.ts, apps/client/src/common/models/Info.ts, apps/client/src/common/models/OntimeSettings.ts, apps/client/src/features/modals/settings-modal/SettingsModal.module.scss, apps/client/src/features/modals/settings-modal/ViewSettingsForm.tsx, apps/server/src/classes/data-provider/__test__/DataProvider.test.ts, apps/server/src/controllers/ontimeController.ts, apps/server/src/models/dataModel.ts, apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/parser.ts, apps/server/src/utils/parserFunctions.ts, apps/server/test-db/db.json, apps/test-db/db.json, demo-db/db.json, e2e/tests/fixtures/test-db.json, packages/types/src/api/ontime-controller/BackendResponse.type.ts, packages/types/src/definitions/core/Settings.type.ts, packages/types/src/index.ts
Improvements are mostly technical, but also adds a link for the CSS override file which users struggle to find
Closes #445
=> feat: small improvements to instance info

apps/client/src/common/hooks/useFollowComponent.ts, apps/client/src/features/operator/Operator.tsx
Fixes issue with distinguishing user initiated scrolling and automated scrolling
Closes #570
=> fix: distinguish user initiated scroll

apps/client/src/features/modals/settings-modal/AliasesForm.tsx, e2e/tests/features/206-alias.spec.ts
Adding tests to cover the alias feature
=> test: alias feature

apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/viewers/timer/Timer.tsx
Allows customisation of the timer view
Closes #589
=> feat: customise timer elements

apps/client/src/common/hooks/useLongPress.tsx, apps/client/src/features/AliasWrapper.tsx, apps/client/src/features/operator/Operator.module.scss, apps/client/src/features/operator/Operator.tsx, apps/client/src/features/operator/edit-modal/EditModal.module.scss, apps/client/src/features/operator/edit-modal/EditModal.tsx, apps/client/src/features/operator/operator-event/OperatorEvent.tsx
Quick PR to implement editing from user fields
Did not do too much testing yet, the values for long press and the show and hide of the overlays can maybe do with tweaking.
It would be great to get some feedback on its usability 
Closes #516
=> feat: allow editing field from operator

.husky/pre-commit, apps/client/package.json, apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.scss, apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.tsx, apps/client/src/features/cuesheet/CuesheetWrapper.module.scss, apps/client/src/features/cuesheet/CuesheetWrapper.tsx, apps/client/src/features/cuesheet/cuesheet-progress/CuesheetProgress.module.scss, apps/client/src/features/cuesheet/cuesheet-progress/CuesheetProgress.tsx, apps/client/src/features/operator/follow-button/FollowButton.module.scss, apps/client/src/features/operator/status-bar/StatusBar.module.scss, apps/client/src/features/operator/status-bar/StatusBar.tsx, apps/client/src/features/operator/status-bar/StatusBarProgress.tsx, apps/client/src/features/operator/status-bar/StatusBarTimers.tsx, apps/client/src/features/viewers/timer/Timer.tsx, apps/client/src/theme/_mixins.scss, apps/electron/package.json, apps/server/package.json, packages/types/package.json, packages/utils/package.json
Shows progress bar in both operator and cuesheet views
Closes #517 
Closes #376 
Closes #130
=> feat: show progress in op and cuesheet

apps/client/package.json, apps/electron/package.json, apps/server/package.json, package.json
Preparing next release `2.21.3` 🥳
=> chore: version bump

apps/client/src/common/components/view-params-editor/ParamInput.tsx, apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/common/components/view-params-editor/types.ts
For cosmetic changes, I've moved the `defaultValue` values to `placeholder`
=> Params Input Placeholders

apps/client/src/features/viewers/backstage/Backstage.tsx
=> fix: backstage end time

apps/client/src/index.tsx
Small cleanup to get rid of errors in sentry
=> refactor: cleanup sentry errors

apps/server/src/app.ts, apps/server/src/external/demo/app.js, apps/server/src/external/demo/index.html, apps/server/src/external/demo/styles.css
=> minimal demo page

apps/client/src/translation/TranslationProvider.tsx, apps/client/src/translation/languages/it.ts
Added italian translation for the client, using the other languages as model.
=> Add italian client translation

apps/client/src/features/modals/settings-modal/AppSettings.tsx
Adds italian to the UI, finishes #655
=> chore: add italian to languages

apps/client/src/features/viewers/studio/StudioClock.scss
=> style: fix missing overrides

apps/server/src/utils/parserFunctions.ts
=> refactor: remove eventdata

apps/server/src/controllers/ontimeController.ts, apps/server/src/controllers/ontimeController.validate.ts, apps/server/src/routes/ontimeRouter.ts, apps/server/src/utils/getFileListFromFolder.ts, packages/types/src/api/ontime-controller/BackendResponse.type.ts, packages/types/src/index.ts
[keep several project files in user folder](https://github.com/cpvalente/ontime/issues/374#top)
=> feat: Several project files user folder (Steps 3-5)

apps/client/src/features/rundown/event-block/EventBlock.module.scss
Im almost certain there is a smarter way to solve this ..... but this works too
closes #676
=> Fix Visual bug on rundown

docker-compose.yml
docker-compose file references wrong ontime version
=> fix docker compose ontime version

.github/workflows/build_docker_v2.yml
This hopefully changes the pipeline to build stable and nightly docker builds of the application
=> nightly builds hopefully

apps/client/src/features/modals/upload-modal/preview/PreviewRundown.tsx, apps/client/src/features/modals/upload-modal/upload-options/ExcelFileOptions.tsx, packages/utils/src/feature/excel-import/excelImport.ts
Here's the adjustment for the excel import, to be able to import the new warning/danger times
=> add fields to import modal

apps/client/package.json, apps/server/package.json, package.json, turbo.json
=> add localdocker build commands

apps/server/src/controllers/integrationController.ts
=> refactor: errors from integrationcontroller

apps/server/src/services/TimerService.ts, apps/server/src/services/timerUtils.ts, apps/server/src/state.ts
small PR to align usage of new state mutations
=> global review

apps/client/package.json, apps/electron/package.json, apps/server/package.json, apps/server/src/utils/parser.ts, package.json
fixes: https://github.com/cpvalente/ontime/issues/713
=> fix: change all ExcelImportMaps to lowercase

apps/client/src/features/control/message/InputRow.tsx
This fixes the issue described in #718
=> fix: message focus

apps/client/src/common/components/input/colour-input/SwatchSelect.module.scss, apps/client/src/common/components/input/time-input/TimeInputWithButton.module.scss, apps/client/src/common/components/input/time-input/TimeInputWithButton.tsx, apps/client/src/features/editors/Editor.module.scss, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/overview/Overview.module.scss, apps/client/src/features/rundown/Rundown.module.scss, apps/client/src/features/rundown/RundownExport.module.scss, apps/client/src/features/rundown/_blockMixins.scss, apps/client/src/features/rundown/delay-block/DelayBlock.module.scss, apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/features/rundown/event-block/RundownIndicators.tsx, apps/client/src/features/rundown/event-editor/EventEditor.module.scss, apps/client/src/index.scss
experimenting with new layout for the editor
=> style: editor layout

apps/server/src/setup.ts
Project list was blank on the first load
=> Fix: Project manager list is blank on the first app load

apps/client/src/features/app-settings/AppSettings.tsx, apps/client/src/features/app-settings/panel/Panel.module.scss, apps/client/src/features/app-settings/panel/PanelUtils.tsx, apps/client/src/features/app-settings/panel/integrations-panel/HttpIntegrations.tsx, apps/client/src/features/app-settings/panel/integrations-panel/IntegrationsPanel.module.css, apps/client/src/features/app-settings/panel/integrations-panel/IntegrationsPanel.tsx, apps/client/src/features/app-settings/panel/integrations-panel/OscIntegrations.tsx
Refactoring of the integrations, UI only for now since we expect significant changes to backend
=> wip: UI for integrations

apps/client/src/common/stores/appModeStore.ts, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/RundownEntry.tsx, apps/client/src/features/rundown/_blockMixins.scss, apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/features/rundown/event-block/EventBlock.tsx, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/rundown/event-block/composite/BlockActionMenu.tsx, apps/client/src/features/rundown/event-block/composite/EventBlockPlayback.tsx, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.module.scss, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.tsx, apps/client/src/theme/ontimeButton.ts
recovers the logic for the app cursor
=> fix: recover cursor logic

apps/client/package.json, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx, apps/electron/package.json, apps/server/package.json, package.json
This fixes a Bug where the danger color isn't shown in the timer view's
This is caused by a wrong order of IF operations.
=> Fix danger time not shown

.github/workflows/build_v3.yml, .github/workflows/test_v3.yml
New Pipeline with upgraded actions. Only manual runs for testing. Haven't made any other changes to the pipeline yet.
=> upgraded pipeline actions

apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/rundown-service/rundownCache.ts
improves the scheduled delays features by including gaps into the calculations
=> refactor: delays account for gaps

apps/server/src/app.ts, apps/server/src/setup.ts, apps/server/src/utils/generateCrashReport.ts
Simple PR to add crash reports to ontime. Not that the app ever crashes...
=> feat: generate crash report

apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/timerUtils.ts
Small improvements to the `time-to-end` logic
=> Time to end

apps/client/src/index.tsx
Small cleanup from alpha 2 feedback
=> refactor: filter sentry errors

apps/client/src/features/rundown/RundownEntry.tsx, apps/client/src/features/rundown/rundown-header/RundownMenu.tsx
Accumulating a few fixes left over with cursor
=> fix: reset focus when deleting all

apps/client/src/common/api/db.ts, apps/client/src/common/api/utils.ts, apps/client/src/features/app-settings/panel/Panel.module.scss, apps/client/src/features/app-settings/panel/project-panel/ProjectListItem.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectPanel.module.scss
it seems that we have some bugs with preparing the file download. I believe this was just a matter of lack of error handling
I took the opportunity to cleanup the logic here and make it easier to reason about
=> refactor: download files from interface

apps/client/src/common/hooks/useScrollIntoView.tsx, apps/client/src/features/app-settings/AppSettings.tsx, apps/client/src/features/app-settings/panel-list/PanelList.module.scss, apps/client/src/features/app-settings/panel-list/PanelList.tsx, apps/client/src/features/app-settings/panel/general-panel/GeneralPanel.tsx, apps/client/src/features/app-settings/panel/integrations-panel/IntegrationsPanel.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectPanel.tsx, apps/client/src/features/app-settings/settingsStore.ts, apps/client/src/features/app-settings/useAppSettingsNavigation.tsx, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/rundown/event-editor/EventEditor.tsx
add navigation based on url for settings
=> feat: url navigation for settings

apps/client/src/common/hooks/useEventAction.ts, apps/client/src/common/stores/editorSettings.ts, apps/client/src/features/app-settings/panel/interface-panel/EditorSettingsForm.tsx, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/RundownEntry.tsx, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.tsx, e2e/tests/features/203-delay-block.spec.ts, e2e/tests/features/204-editor-crud.spec.ts, e2e/tests/features/205-operator.spec.ts, package.json, pnpm-lock.yaml
Some small changes to the editor options
- quick add options has a shortcut for link
- it is now possible to add an event default time in the settings, I set the default to 10min
=> Quick options

apps/server/src/services/RestoreService.ts
small performance improvement of 0.05ms
=> refactor: save object on restore

apps/server/src/services/TimerService.ts
Fixes an issue where the time to update didnt account for midnight rollover
Fixes #844
=> fix: account for midnight rollover

apps/server/src/api-data/db/db.controller.ts, apps/server/src/classes/data-provider/DataProvider.ts, apps/server/src/services/project-service/ProjectService.ts, apps/server/src/services/rundown-service/RundownService.ts
fixing issue with excel import
Also doing some cleanup around project patching
=> Apply project

packages/utils/src/validate-action/validatePlayback.ts
Recovers possibility to go from play to roll mode.
=> refactor: allow transition from roll to playback

apps/client/package.json, apps/client/src/common/components/navigation-menu/ProductionNavigationMenu.tsx, apps/client/src/features/app-settings/panel/sources-panel/import-map/ImportMapForm.tsx, apps/server/package.json, apps/server/src/api-data/url-presets/urlPresets.controller.ts, apps/server/src/classes/data-provider/DataProvider.ts, apps/server/src/services/rundown-service/RundownService.ts, apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/services/sheet-service/sheetUtils.ts, package.json, packages/types/package.json, packages/utils/package.json, pnpm-lock.yaml
small lint cleanups
@alex-Arc, the logic around spreadsheets is a bit heavy and I thought we could slowly try to simplify, can you sanity check the change?
=> Alpha 3 cleanup

apps/client/src/AppRouter.tsx, apps/client/src/common/components/navigation-menu/FloatingNavigation.tsx, apps/client/src/common/components/navigation-menu/NavigationMenu.tsx, apps/client/src/common/components/navigation-menu/ProductionNavigationMenu.tsx, apps/client/src/common/components/navigation-menu/ViewNavigationMenu.tsx, apps/client/src/common/hooks/useWindowTitle.ts, apps/client/src/features/cuesheet/CuesheetWrapper.module.scss, apps/client/src/features/cuesheet/CuesheetWrapper.tsx, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/operator/Operator.tsx, apps/client/src/features/operator/OperatorExport.tsx, apps/client/src/features/overview/Overview.module.scss, apps/client/src/features/overview/Overview.tsx, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/clock/Clock.tsx, apps/client/src/features/viewers/countdown/Countdown.tsx, apps/client/src/features/viewers/lower-thirds/LowerThird.tsx, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/public/Public.tsx, apps/client/src/features/viewers/studio/StudioClock.tsx, apps/client/src/features/viewers/timer/Timer.tsx, e2e/tests/000-upload-showfile.spec.ts, e2e/tests/features/206-url-preset.spec.ts, e2e/tests/features/301-spreadsheet-import.spec.ts
Adding changes to navigation in production views
- Editor
- Cuesheet
- Operator
=> Navigation3

apps/server/package.json, apps/server/src/app.ts, pnpm-lock.yaml
wip
trying to improve server performance
=> feat: chaching

.eslintrc, apps/client/src/common/components/navigation-menu/NavigationMenu.module.scss, apps/client/src/common/components/navigation-menu/NavigationMenu.tsx, apps/client/src/common/components/navigation-menu/ProductionNavigationMenu.tsx, apps/client/src/common/components/navigation-menu/ViewNavigationMenu.tsx, apps/client/src/common/components/protect-route/PinPage.tsx, apps/client/src/common/components/protect-route/ProtectRoute.module.scss, apps/client/src/common/components/view-params-editor/ViewParamsEditor.module.scss, apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx, apps/client/src/common/hooks-query/useCustomFields.ts, apps/client/src/common/hooks-query/useHttpSettings.ts, apps/client/src/common/hooks-query/useInfo.ts, apps/client/src/common/hooks-query/useOscSettings.ts, apps/client/src/common/hooks-query/useProjectData.ts, apps/client/src/common/hooks-query/useProjectList.ts, apps/client/src/common/hooks-query/useRundown.ts, apps/client/src/common/hooks-query/useSettings.ts, apps/client/src/common/hooks-query/useUrlPresets.ts, apps/client/src/common/hooks-query/useViewSettings.ts, apps/client/src/features/app-settings/panel/general-panel/GeneralPanel.tsx, apps/client/src/features/app-settings/settingsStore.ts, apps/client/src/features/control/message/MessageControl.tsx, apps/client/src/features/operator/OperatorExport.tsx, apps/client/src/features/viewers/timer/Timer.scss, apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/timerUtils.ts, e2e/tests/features/206-url-preset.spec.ts
small tweaks from user feedback on alpha.3
=> V3 feedback

apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/api-data/excel/excel.service.ts, apps/server/src/classes/simple-timer/SimpleTimer.ts, apps/server/src/services/RestoreService.ts, apps/server/src/services/project-service/ProjectService.ts, apps/server/src/services/rundown-service/RundownService.ts, apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/setup/loadDb.ts, apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/parser.ts, apps/server/src/utils/parserFunctions.ts, apps/server/src/utils/parserUtils.ts
Fixing issue raised in #863 by implementing an extra flag in all mutation which indicates whether a mutation actually happenned
We can use this flag to avoid doing side effects.
In future™, we could also use this to do better response codes
Took the chance to do some typescript improvements and simplify initial parsing of json data
=> Typescript null

apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx, apps/client/src/common/utils/styleUtils.ts, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx, e2e/tests/features/207-view-params.spec.ts
fix issue with parameters being cleared on submit
=> fix: params editor

apps/client/src/common/components/schedule/ScheduleContext.tsx, apps/client/src/common/components/view-params-editor/constants.ts
small fix to prevent overflow in the views with schedule
=> style: prevent overflow on defaults

apps/client/src/features/app-settings/panel/shutdown-panel/ShutdownPanel.tsx, apps/client/src/features/rundown/rundown-header/RundownMenu.tsx, apps/client/src/theme/OntimeAlert.ts, apps/client/src/theme/theme.ts, apps/client/vite.config.js, e2e/tests/000-upload-showfile.spec.ts, e2e/tests/features/203-delay-block.spec.ts, e2e/tests/features/204-editor-crud.spec.ts, e2e/tests/features/205-operator.spec.ts, e2e/tests/features/301-spreadsheet-import.spec.ts
Adds a confirmation prompt to deleting the entire rundown action
=> Confirm delete

apps/server/src/services/TimerService.ts, apps/server/src/services/integration-service/IntegrationService.ts, apps/server/src/services/runtime-service/RuntimeService.ts
This is more likely the fix we are looking for when preventing stale data in integrations
However it is a large change and we should take some time to investigate
=> refactor: runtime side effects

apps/client/package.json, apps/client/src/App.tsx, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/viewers/backstage/Backstage.scss, apps/client/src/index.scss, apps/electron/src/menu/applicationMenu.js, apps/server/src/utils/__tests__/parser.test.ts, pnpm-lock.yaml
Some small tweaks from feedback on betas
- Settings button toggles to a X 
- fix text in macOS menu
- remove extra padding in backstage screen
Tooling:
- updates to typeface
- fix test, order of objects is not guaranteed in javascript
=> Beta 2 feedback

packages/utils/package.json, packages/utils/src/date-utils/timeFormatting.test.ts, packages/utils/src/date-utils/timeFormatting.ts, pnpm-lock.yaml
Hello,
this PR is related to #914.
- Removed the luxon dependencies (types, luxon) and the related imports.
- Refactored the function formatFromMillis(), which used methods from luxon to a custom one without dependencies.
- Added tests for formatFromMillis()
Test passed:
Edit:
I added the functionality test before changing the "luxon method" to be sure that my function works as intended.
=> #914 Refactor: Luxon-Depenency, formatFromMillis()

test-db/db.json
Small update to the testdb
This is harmless™ and attempts to match the db to the parsing order so that we get cleaner diffs
=> chore: update element order

apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/utils/fileManagement.ts
=> fix: filename may not exist

apps/client/src/features/editors/Editor.module.scss, apps/client/src/features/rundown/RundownExport.module.scss, apps/client/src/features/rundown/event-editor/EventEditorEmpty.module.scss, apps/client/src/features/rundown/event-editor/EventEditorEmpty.tsx, apps/client/src/theme/theme.ts
Small style tweaks on interface.
I will likely leave this around until the next release 
- improve consistency of spacing in editor
- improve readability of shortcut section
- make rundown section take entire screen in HD screens
=> style: consistent spacing in editor

.dockerignore, DEVELOPMENT.md, Dockerfile
Hello,
This is a simple change to do a multi-stage build.
This might be useful to avoid installing node / pnpm on the host and running build commands before packaging the result to the image. 
It will be helpful for CI/CD pipelines
=> Multistage docker build

.github/workflows/build_docker.yml, Dockerfile, package.json, turbo.json
I've tested this locally and all 4 platforms now build successfully.
=> fix docker multi-architecture build

apps/client/src/common/components/input/time-input/TimeInput.tsx, apps/client/src/common/components/input/time-input/TimeInputWithButton.module.scss
Fixes issue with the overflow in time inputs
Closes #959
=> style: fix input overflow

apps/client/src/common/components/input/time-input/TimeInput.tsx, apps/client/src/common/components/input/time-input/TimeInputWithButton.module.scss, apps/client/src/common/components/input/time-input/TimeInputWithButton.tsx
=> style: input text alignment

apps/client/package.json, apps/client/src/App.tsx, apps/client/src/common/api/rundown.ts, apps/client/src/common/components/context-menu/ContextMenu.tsx, apps/client/src/common/hooks/useEventAction.ts, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/RundownEntry.tsx, apps/client/src/features/rundown/RundownExport.tsx, apps/client/src/features/rundown/delay-block/DelayBlock.tsx, apps/client/src/features/rundown/event-block/EventBlock.tsx, apps/client/src/features/rundown/useEventSelection.ts, apps/server/src/api-data/rundown/rundown.controller.ts, apps/server/src/api-data/rundown/rundown.router.ts, apps/server/src/api-data/rundown/rundown.validation.ts, apps/server/src/services/rundown-service/RundownService.ts, apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/rundown-service/rundownCache.ts, packages/utils/src/array-utils/arrayUtils.ts, pnpm-lock.yaml
adding delete action for multiple selection
=> refactor: context menu actions

apps/client/src/common/components/view-params-editor/constants.ts
=> add notes to secondaryOptions in timer view

apps/server/src/api-integration/integration.controller.ts, apps/server/src/api-integration/integration.utils.ts
we only need to force lower case on custom fields
=> fix: change api isPublic

apps/server/src/app.ts, apps/server/src/setup/index.ts
should I incorporate some of the stuff from #904 ?
=> Clear upload folder on startup

apps/client/src/features/app-settings/panel/integrations-panel/OscIntegrations.tsx, apps/server/src/api-data/db/db.controller.ts, apps/server/src/services/project-service/ProjectService.ts
closes #1026
i'm unsure on how the ProjectService works but I think this is the missing step?
=> fix: osc new project

apps/server/src/services/timerUtils.ts, apps/server/src/stores/runtimeState.ts
This PR introduces code to make roll ignore events prior to the currently loaded
=> refactor: continue roll

apps/client/src/features/control/playback/aux-timer/AuxTimer.module.scss, apps/client/src/features/control/playback/aux-timer/AuxTimer.tsx
We got some users asking where the Auxiliary timer was, this hopefully simplifies the interface
=> style: add label to auxiliary timer

apps/client/src/features/control/playback/timer-display/TimerDisplay.tsx, apps/server/src/services/runtime-service/rundownService.utils.ts, packages/utils/src/date-utils/conversionUtils.ts, packages/utils/src/date-utils/timeFormatting.test.ts, packages/utils/src/date-utils/timeFormatting.ts
=> refactor: fix missed first update

apps/client/src/features/cuesheet/Cuesheet.module.scss, apps/client/src/features/cuesheet/cuesheet-table-elements/CuesheetHeader.tsx, apps/client/src/features/cuesheet/cuesheet-table-elements/EventRow.tsx, apps/client/src/features/cuesheet/cuesheet-table-settings/CuesheetTableSettings.tsx
=> keep the index row as a colour chip

apps/client/src/features/control/playback/playback-timer/PlaybackTimer.tsx, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx, apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/timerUtils.ts, packages/types/src/definitions/runtime/TimerState.type.ts
=> Fix pending

apps/server/src/utils/__tests__/parserFunctions.test.ts, apps/server/src/utils/parserFunctions.ts
=> Fix: link events in sheet when there is nothing to link

apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/viewers/timer/Timer.tsx
=> Custom for timer title

apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldForm.tsx, apps/client/src/features/app-settings/panel/sources-panel/SourcesPanel.module.scss, apps/client/src/features/app-settings/panel/sources-panel/SourcesPanel.tsx, apps/client/src/features/app-settings/panel/sources-panel/import-map/ImportMapForm.tsx
This PR adds better handling of error states in the google sheet flow
=> refactor: improve error states in spreadsheet flow

apps/client/package.json, apps/electron/package.json, apps/server/package.json, package.json
Recent release did not update version number; this PR does ;)
Closes #1073 (after re-release generated)
=> bump version to 3.2.0

apps/client/src/features/app-settings/panel/integrations-panel/integrationUtils.ts, apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/__tests__/parserFunctions.test.ts, packages/types/src/definitions/core/TimerLifecycle.type.ts
- onWarning when timer transitions to warning phase
- onDanger when timer transitions to danger phase
=> add warning and danger transitions as timer life cycle events

apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/rundown-service/__tests__/rundownCacheUtils.test.ts, apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/services/rundown-service/rundownCacheUtils.ts
ensures persistence of custom fields
=> fix: persistence of custom fields

.github/workflows/build_cli.yml
https://docs.npmjs.com/generating-provenance-statements
=> add permission for provenance publishing

apps/server/src/app.ts, apps/server/src/classes/Logger.ts, apps/server/src/classes/data-provider/__tests__/DataProvider.test.ts, apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/services/sheet-service/SheetService.ts, apps/server/src/services/sheet-service/__tests__/sheetUtils.test.ts, apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/utils/__tests__/parserUtils.test.ts, apps/server/src/utils/networkInterfaces.ts, apps/server/src/utils/parserUtils.ts, apps/server/tsconfig.json
Small PR to change some types of easy things
It does not change business logic
Before
Found 281 errors in 37 files.
After
Found 228 errors in 29 files.
=> refactor: improve typing

apps/cli/package.json, apps/client/package.json, apps/electron/package.json, apps/server/package.json, apps/server/tsconfig.json, package.json
=> hotfix-build

apps/client/src/features/operator/operator-event/OperatorEvent.module.scss
=> style: add background to highlight

apps/client/src/common/components/title-card/TitleCard.scss, apps/client/src/common/components/title-card/TitleCard.tsx, apps/client/src/features/operator/operator-event/OperatorEvent.module.scss, apps/client/src/features/rundown/event-editor/composite/EventTextInput.tsx, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/countdown/Countdown.tsx, apps/client/src/features/viewers/lower-thirds/LowerThird.scss, apps/client/src/features/viewers/public/Public.tsx, apps/client/src/features/viewers/studio/StudioClock.scss, apps/client/src/features/viewers/studio/StudioClock.tsx, apps/client/src/features/viewers/timer/Timer.scss, apps/client/src/features/viewers/timer/Timer.tsx, apps/client/src/theme/_mixins.scss, apps/client/vite.config.js
Since we dont enforce limits in API layer, it makes sense to also not do so in the UI.
The trade off being that the user is in full control over this and can make the views ugly with cut titles
=> refactor: remove size limits in title

apps/cli/package.json, apps/client/package.json, apps/electron/package.json, apps/server/package.json, package.json
Bumping version before new release
=> bump version to 3.3.3

apps/client/src/features/viewers/common/viewUtils.ts
=> fix: format clock as timer

package.json, pnpm-lock.yaml
=> remove unused husky dependency

apps/server/src/api-data/rundown/rundown.controller.ts, apps/server/src/api-data/rundown/rundown.router.ts
`ip:port/data/rundown` -> array with rundown
`ip:port/data/rundown/paginated?offset=0&limit=10` -> object with rundown section and total event number
=> restore rundownGetAll

apps/electron/main.js, apps/electron/src/menu/applicationMenu.js
#1154 
unsure if `win.loadUrl` is the best way
=> about in electron help menu

apps/client/src/common/hooks/useSocket.ts, apps/client/src/features/overview/Overview.tsx
=> show time in block

apps/server/src/services/runtime-service/RuntimeService.ts
fixes issue with playback continuing when an event is deleted
this also means that playback is stopped if user changes the current event to skip (not possible in app UI)
=> fix: stop playback when event is deleted

apps/client/src/features/app-settings/panel/sources-panel/import-map/ImportMapForm.tsx
Fixes issue with the submit buttons being enabled if we have worksheet errors
=> fix: check worksheet errors before submit

apps/server/src/services/rundown-service/__tests__/delayUtils.test.ts, apps/server/src/services/rundown-service/delayUtils.ts
Fixes issue described in #1230
I tried testing that all the delays are the same when applied and when they are visible (orange indicators), would be good to sanity check
=> fix: apply delay

apps/server/src/services/project-service/ProjectService.ts
small PR to add awaits to calls to init the rundown
=> refactor: await init rundown

apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/timerUtils.ts
=> Fix: time-to-end offset

apps/client/src/features/viewers/timeline/TimelineEntry.tsx, apps/client/src/features/viewers/timeline/TimelinePage.tsx, apps/client/src/features/viewers/timeline/__tests__/timeline.utils.test.ts, apps/client/src/features/viewers/timeline/timeline.utils.ts
fixes some weirdness with calculating time to start in timeline
=> Time to start

apps/client/src/theme/_ontimeStyles.scss
user feedback: blink is too subtle and fails at grabbing the speakers attention
=> refactor: blink style

apps/client/src/common/components/copy-tag/CopyTag.tsx, apps/client/src/features/app-settings/panel/network-panel/NetworkInterfaces.module.scss, apps/client/src/features/app-settings/panel/network-panel/NetworkInterfaces.tsx, apps/client/src/features/app-settings/panel/sources-panel/GSheetSetup.tsx, apps/client/src/features/rundown/event-editor/EventEditor.tsx
user feedback: "we would like to be able to copy the URL from the network interface"
This also prepares the components for including in the view navigation
=> refactor: network interfaces can be copied or followed

apps/client/src/common/stores/runtime.ts, apps/server/src/app.ts, apps/server/src/services/message-service/MessageService.ts, apps/server/src/services/message-service/__tests__/MessageService.test.ts, packages/types/src/definitions/runtime/RuntimeStore.ts, packages/types/src/index.ts
Making the message service stateless
=> Stateless messages

apps/client/src/externals.ts, apps/client/src/features/app-settings/panel/feature-settings-panel/FeatureSettings.module.scss, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldEntry.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldForm.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFields.tsx, apps/client/src/theme/OntimeAlert.ts
=> Client cleanup

apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/rundown/event-block/composite/EventBlockReporter.module.scss, apps/client/src/features/rundown/event-block/composite/EventBlockReporter.tsx
not sure if this is what you needed
Just fixed some small things with the grid and wrote some dirty styling
I have removed the blinking animation in favour of the logic we prefer
lets chat
=> refactor: simplify styling

apps/client/src/common/api/db.ts, apps/client/src/common/api/session.ts, apps/client/src/common/hooks-query/useInfo.ts, apps/client/src/common/models/Info.ts, apps/client/src/features/app-settings/panel/general-panel/ViewSettingsForm.tsx, apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/api-data/db/db.controller.ts, apps/server/src/api-data/db/db.router.ts, apps/server/src/api-data/index.ts, apps/server/src/api-data/session/session.controller.ts, apps/server/src/api-data/session/session.router.ts, apps/server/src/api-data/session/session.service.ts, apps/server/src/api-integration/integration.controller.ts, apps/server/src/services/project-service/ProjectService.ts, apps/server/src/services/runtime-service/RuntimeService.ts, packages/types/src/api/ontime-controller/BackendResponse.type.ts, packages/types/src/index.ts
This PR exposes some runtime information that will come in handy for server environments
I have also decided to create a new resource for `session` that gathers information related to the server process
=> feat: session data

apps/client/src/views/timeline/Timeline.module.scss
making sure the timeline styles are overrideable
=> refactor: timeline has overrideable styles

apps/server/src/setup/index.ts, apps/server/src/setup/loadDemo.ts, apps/server/src/setup/loadStyles.ts
seems like i forgot to copy the readme files to the user installation folders
=> refactor: populate readme on start

apps/client/src/common/hooks/useEventAction.ts, apps/client/src/features/rundown/event-block/EventBlock.tsx, apps/client/src/features/rundown/time-input-flow/TimeInputFlow.tsx, apps/server/src/services/rundown-service/rundownCacheUtils.ts
to improve setting the entire rundown as link start, we add batch functions to the context menu
NOTE: please be critical, I am not sure if this is a good idea
=> feat: add link to context menu

apps/client/src/features/app-settings/panel/sources-panel/SourcesPanel.tsx, apps/client/src/features/app-settings/panel/sources-panel/import-map/ImportMapForm.tsx
This PR resets the form state on cancel and fixes the issue described in #1289
I am also revoking authentication on google sheet cancel, that may be incorrect
=> refactor: clear state on sheet flows

apps/client/src/features/cuesheet/Cuesheet.tsx, apps/client/src/features/operator/operator-event/OperatorEvent.module.scss, apps/server/src/user/styles/override.css
clarify that production views cannot have style overrides
=> refactor: no style overrides in production views

apps/client/src/features/app-settings/panel/interface-panel/EditorSettingsForm.tsx, apps/client/src/features/control/message/TimerPreview.tsx, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/rundown/event-editor/composite/EventEditorTimes.tsx, apps/client/src/features/viewers/common/viewUtils.ts, apps/client/src/features/viewers/timer/Timer.tsx, packages/types/src/definitions/TimerType.type.ts
This PR adds a new timer type `None` as described in #1311
=> feat: add time type none

apps/client/src/common/hooks-query/useRundown.ts
Fix an issue where loading a new project could give us stale date until the user forced refresh
=> fix: prevent stale data on project change

apps/client/package.json, apps/client/src/common/api/constants.ts, apps/client/src/common/components/navigation-menu/NavigationMenu.tsx, apps/client/src/common/components/protect-route/ProtectRoute.tsx, apps/client/src/common/hooks-query/useAppVersion.ts, apps/client/src/common/hooks/useMemoisedFn.ts, apps/client/src/common/hooks/useSocket.ts, apps/client/src/common/utils/socket.ts, apps/client/src/externals.ts, apps/client/src/features/app-settings/panel/network-panel/NetworkInterfaces.tsx, apps/client/src/features/app-settings/panel/network-panel/NetworkLogPanel.tsx, apps/client/src/features/app-settings/panel/shutdown-panel/ShutdownPanel.tsx, apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/app.ts, packages/types/src/definitions/runtime/RuntimeStore.ts, packages/types/src/definitions/runtime/RuntimeStore.type.ts
simple utilities for ontime running in docker
=> Socket pong

apps/client/src/AppRouter.tsx, apps/client/src/viewerConfig.ts, apps/client/src/views/project-info/ProjectInfo.scss, apps/client/src/views/project-info/ProjectInfo.tsx, apps/client/src/views/project-info/backstage-info/BackstageInfo.tsx, apps/client/src/views/project-info/projectInfo.options.ts, apps/client/src/views/project-info/public-info/PublicInfo.tsx, apps/client/src/views/timeline/TimelinePage.tsx, apps/electron/src/menu/applicationMenu.js, e2e/tests/002-view-navigation.spec.ts
=> Project view

apps/client/src/features/cuesheet/Cuesheet.module.scss, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/views/project-info/ProjectInfo.tsx
Some issues found in a recent user review, mostly stylistic
however, it seems that introducing the copy-paste of blocks, broke general availability of copy-paste function in the editor
That is not ideal and hopefully the code change resolves it
=> project review

apps/client/src/features/app-settings/panel/general-panel/GeneralPanelForm.tsx, apps/client/src/features/app-settings/quick-start/QuickStart.tsx, apps/client/src/translation/TranslationProvider.tsx, apps/client/src/translation/languages/zh.ts
This PR adds support for chinese translations as mentioned in #1324
=> feat: add support for chinese

apps/client/src/AppRouter.tsx, apps/client/src/externals.ts, apps/client/vite.config.js, apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/app.ts, apps/server/src/externals.ts
e2e is broken in git but works localy
and the sidebar links needs updating
=> Prefix fix

apps/server/src/classes/simple-timer/SimpleTimer.ts, apps/server/src/classes/simple-timer/__tests__/SimpleTimer.test.ts, apps/server/src/services/aux-timer-service/AuxTimerService.ts
@7omas thanks for finding this
#1357
=> create addTime function in simple timer

apps/client/src/features/viewers/studio/StudioClock.scss
small fix to prevent overflow in studio clock
=> fix: prevent overflow

apps/client/src/common/components/state/EmptyPage.module.scss, apps/client/src/common/components/state/EmptyPage.tsx, apps/client/src/views/project-info/ProjectInfo.tsx
create a better empty state for the project info page
=> refactor: improve empty state for project info

apps/client/src/features/app-settings/panel/integrations-panel/OscIntegrations.tsx, apps/client/src/features/app-settings/panel/shutdown-panel/ShutdownPanel.tsx, apps/server/src/app.ts, apps/server/src/externals.ts
adding a small note that OSC doesnt work
I couldnt think of anything else that would not work
do you think the note is good enough?
=> chore: note service limitations

apps/client/src/common/components/view-params-editor/ViewParamsEditor.module.scss, apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx, apps/client/src/theme/_ontimeStyles.scss
This is a simple proposal for tweaking the presentation of the feature
Waiting for some user feedback
=> refactor: style tweaks

apps/server/src/services/timerUtils.ts, apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/stores/runtimeState.ts, packages/utils/index.ts, packages/utils/src/playback-utils/playbackstate.ts
Pulled out of the reporter PR
I need it in other places befor the reporter PR is merged
=> extract isPlaybackActive to a global util function

packages/utils/src/array-utils/arrayUtils.test.ts, packages/utils/src/array-utils/arrayUtils.ts
small change to improve the logic of the delete utility
=> refactor: simplify logic

apps/client/src/common/utils/keyEvent.ts, apps/client/src/features/app-settings/panel/integrations-panel/OscIntegrations.tsx
small commit to extract the prevent exit on escape utility
this should be applied to most forms in the panel later on
=> refactor: extract utility

apps/client/src/features/app-settings/panel-utils/PanelUtils.module.scss, apps/client/src/features/app-settings/panel-utils/PanelUtils.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/UrlPresetsForm.tsx
extracting some small changes to the panel styles
=> Panel styles

apps/server/src/app.ts, apps/server/src/middleware/bodyParser.ts, apps/server/src/middleware/staticGZip.ts, apps/server/src/utils/network.ts
This is a small PR with a few objectives
- ~~implement rate limiting for http~~
- organise middleware
- stop port change in dev
I also refactored the `serverTryDesiredPort` slightly to improve the typing and (hopefully) simplify the logic.
The indentation changes make it look like the change is larger than it is. Let me know if you have questions
Notes: 
- return is necessary after resolve / reject since this do not stop code execution. ie: the promise state cannot be changed, but the remaining code would still run
- what do you think of the rate limits? I believe these should be safe for user scenarios but still block (script gone rogue) issues?
=> Middleware

apps/client/src/common/components/protect-route/ProtectRoute.module.scss
cleaning up the styles of the pin page
=> refactor: cleanup pin styles

apps/client/src/features/editors/welcome/Welcome.tsx
looks like I managed to mess up the welcome checkbox and it doesnt show checked by default now
=> fix: show correct state for welcome option

apps/client/src/features/app-settings/AppSettings.tsx, apps/client/src/features/app-settings/panel/automations-panel/AutomationForm.module.scss, apps/client/src/features/app-settings/panel/client-control-panel/ClientControlPanel.module.scss, apps/client/src/features/app-settings/panel/client-control-panel/ClientList.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/FeatureSettings.module.scss, apps/client/src/features/app-settings/panel/feature-settings-panel/UrlPresetsForm.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldEntry.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldForm.tsx, apps/client/src/features/app-settings/panel/general-panel/GeneralPanel.module.scss, apps/client/src/features/app-settings/panel/general-panel/GeneralPanelForm.tsx, apps/client/src/features/app-settings/panel/general-panel/ViewSettingsForm.tsx, apps/client/src/features/app-settings/panel/network-panel/NetworkInterfaces.module.scss, apps/client/src/features/app-settings/panel/network-panel/NetworkInterfaces.tsx, apps/client/src/features/app-settings/panel/project-panel/ManageProjects.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectCreateForm.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectData.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectForm.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectListItem.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectMergeForm.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectPanel.module.scss, apps/client/src/features/app-settings/panel/sources-panel/GSheetSetup.tsx, apps/client/src/features/app-settings/panel/sources-panel/ImportReview.tsx, apps/client/src/features/app-settings/panel/sources-panel/SourcesPanel.module.scss, apps/client/src/features/app-settings/panel/sources-panel/import-map/ImportMapForm.tsx, apps/client/src/features/log/Log.module.scss, apps/client/src/features/log/Log.tsx
small improvements to the UX and UI in settings, mostly handling escape behaviour in forms
=> Settings UI

apps/client/src/common/hooks/useSocket.ts, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/RundownEntry.tsx, apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/features/rundown/event-block/EventBlock.tsx, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/rundown/event-block/composite/EventBlockChip.module.scss, apps/client/src/features/rundown/event-block/composite/EventBlockChip.tsx, apps/client/src/theme/_ontimeStyles.scss
dependent on #1448 
calculates and shows the time until an expected event start in the editor ui
=> Timeuntil in UI

apps/client/src/features/app-settings/panel/general-panel/GeneralPanelForm.tsx, apps/client/src/features/app-settings/panel/general-panel/GeneralPinInput.tsx, apps/client/src/features/operator/operator-event/OperatorEvent.module.scss
Small fixes from user feedback:
- use variables in operator to allow user to style
- fix issue with non alphanumeric characters in pincode
- allow multiline text in custom fields
=> Small fixes

apps/client/src/features/app-settings/panel/automations-panel/AutomationPanel.tsx, apps/client/src/features/app-settings/panel/automations-panel/automationUtils.ts, apps/client/src/features/app-settings/useAppSettingsMenu.tsx
small tweaks from user feedback
- swap panel order in automation settings
- allow using properties of next event in filters
=> Automation review

apps/server/src/api-data/db/db.controller.ts, apps/server/src/api-data/db/db.validation.ts, apps/server/src/services/project-service/ProjectService.ts
Fixes an issue where creating a file from the quick menu will not add the extension name
=> fix: project created without extension

apps/cli/package.json, apps/client/package.json, apps/electron/package.json, apps/server/package.json, apps/server/src/adapters/OscAdapter.ts, package.json
Fixes an issue where we would assume any UDP message on our OSC IN port is a well formed OSC message
As reported in #1500
=> Fix OSC read buffer issue

apps/client/src/common/components/input/colour-input/SwatchPicker.tsx, apps/client/src/common/components/navigation-menu/FloatingNavigation.tsx, apps/client/src/common/components/navigation-menu/ViewLockedIcon.tsx, apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx, apps/client/src/common/hooks/useFadeOutOnInactivity.tsx, apps/client/src/features/app-settings/panel/sources-panel/GSheetSetup.tsx, apps/server/src/adapters/OscAdapter.ts, apps/server/src/api-data/automation/__tests__/automation.dao.test.ts, apps/server/src/api-data/automation/__tests__/automation.service.test.ts, apps/server/src/api-data/automation/automation.controller.ts, apps/server/src/api-data/automation/automation.dao.ts, apps/server/src/api-data/automation/automation.service.ts, apps/server/src/app.ts, apps/server/src/services/sheet-service/SheetService.ts, apps/server/src/setup/loadDemo.ts, apps/server/src/stores/EventStore.ts, apps/server/src/utils/development.ts, apps/server/src/utils/parserUtils.ts
small PR with some harmless code improvements
=> Deepsource review

apps/client/src/features/app-settings/panel/automations-panel/AutomationForm.module.scss, apps/client/src/features/app-settings/panel/automations-panel/AutomationForm.tsx, apps/client/src/features/app-settings/panel/automations-panel/OntimeActionForm.tsx, apps/client/src/features/app-settings/panel/automations-panel/template-input/TemplateInput.tsx, apps/client/src/features/app-settings/panel/automations-panel/template-input/__tests__/templateInput.utils.test.ts, apps/client/src/features/app-settings/panel/automations-panel/template-input/templateInput.utils.ts, apps/electron/src/menu/applicationMenu.js, apps/server/src/api-data/automation/__tests__/automation.validation.test.ts, apps/server/src/api-data/automation/automation.controller.ts, apps/server/src/api-data/automation/automation.service.ts, apps/server/src/api-data/automation/automation.utils.ts, apps/server/src/api-data/automation/automation.validation.ts, apps/server/src/api-data/automation/clients/ontime.client.ts, apps/server/src/app.ts, packages/types/src/definitions/core/Automation.type.ts, packages/types/src/definitions/runtime/MessageControl.type.ts, packages/types/src/index.ts, packages/types/src/utils/guards.ts
Fix a few issues with automation
- Missing reference for args field in the OSC input
- Non unique keys in filter items
Also important:
- Allow a select amount of Ontime actions to be automated from the automations flow
=> Automations review

apps/client/src/common/components/client-modal/RedirectClientModal.module.scss, apps/client/src/common/components/client-modal/RedirectClientModal.tsx, apps/client/src/common/components/info/Info.module.scss, apps/client/src/common/utils/socket.ts, apps/client/src/features/app-settings/panel/client-control-panel/ClientList.tsx, apps/server/src/adapters/WebsocketAdapter.ts, e2e/tests/features/210-client-remote.spec.ts, packages/types/src/definitions/Clients.type.ts
This is a small code change to allow the redirect modal to use URL presets
=> feat: allow redirecting to preset

apps/client/src/translation/languages/de.ts, apps/client/src/translation/languages/en.ts, apps/client/src/translation/languages/es.ts, apps/client/src/translation/languages/fr.ts, apps/client/src/translation/languages/hu.ts, apps/client/src/translation/languages/it.ts, apps/client/src/translation/languages/no.ts, apps/client/src/translation/languages/pl.ts, apps/client/src/translation/languages/pt.ts, apps/client/src/translation/languages/sv.ts, apps/client/src/translation/languages/zh.ts, apps/client/src/views/project-info/ProjectInfo.scss, apps/client/src/views/project-info/ProjectInfo.tsx, apps/client/src/views/project-info/backstage-info/BackstageInfo.tsx, apps/client/src/views/project-info/public-info/PublicInfo.tsx
design review for the project view
Not much to do here, just making sure we use the variables and the translated strings
=> refactor: project info design review

apps/client/package.json, apps/client/src/common/components/input/text-input/useReactiveTextInput.tsx, apps/client/src/common/utils/lazyEvaluate.ts, apps/client/src/views/cuesheet/CuesheetPage.tsx, apps/client/src/views/cuesheet/cuesheet-table/CuesheetTable.module.scss, apps/client/src/views/cuesheet/cuesheet-table/CuesheetTable.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/BlockRow.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/CuesheetBody.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/CuesheetHeader.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/DelayRow.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/EventRow.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/MultiLineCell.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/SingleLineCell.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/SortableCell.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TextLikeInput.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TimeInput.tsx, pnpm-lock.yaml
* refactor: cuesheet table body
* feat: add table navigation
=> feat: add table navigation to cuesheet table (#1483)

apps/server/src/services/runtime-service/rundownService.utils.ts
=> also update clock on seconds rounding

apps/client/src/features/app-settings/panel/automations-panel/AutomationForm.tsx
Fixes link to documentation as mentioned in #1543
=> fix: link to variables

apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/rundown-service/rundownCache.utils.ts
Targeting this to v4 to leverage the metadata generator which does not exist in v3
=> fix delay positioning in gaps

apps/client/package.json, apps/client/src/common/api/assets.ts, apps/client/src/features/app-settings/panel-utils/PanelUtils.module.scss, apps/client/src/features/app-settings/panel-utils/PanelUtils.tsx, apps/client/src/features/app-settings/panel/general-panel/StyleEditor.module.scss, apps/client/src/features/app-settings/panel/general-panel/StyleEditor.tsx, apps/client/src/features/app-settings/panel/general-panel/StyleEditorModal.module.scss, apps/client/src/features/app-settings/panel/general-panel/StyleEditorModal.tsx, apps/client/src/features/app-settings/panel/general-panel/ViewSettingsForm.tsx, apps/client/src/features/app-settings/panel/general-panel/prismjs.d.ts, apps/server/package.json, apps/server/scripts/bundleCss.ts, apps/server/src/api-data/assets/assets.controller.ts, apps/server/src/api-data/assets/assets.router.ts, apps/server/src/api-data/assets/assets.service.ts, apps/server/src/api-data/assets/assets.validation.ts, apps/server/src/api-data/index.ts, apps/server/src/user/styles/bundledCss.ts, pnpm-lock.yaml
This is a PR to prepare the CSS editor to merge
- tweak styles to match other modals
- add validation and error handling
- cleanup debug code
- revert to demo CSS and clarify prompt
=> feat: css editor (#1542)

apps/client/src/features/viewers/studio/StudioClock.scss
Fix as discussed in https://github.com/cpvalente/ontime/issues/1585
=> fix - fix studio clock sizing when timer seconds are hidden  !1585

apps/client/src/externals.ts, apps/client/vite.config.js
This is to help when building authentication system
as it gets around the CORS issue in dev
and I think it is a bit cleaner to not have dev logic in the code
=> let vite be the proxy to the dev server

apps/server/src/api-data/session/session.service.ts, packages/types/src/api/ontime-controller/BackendResponse.type.ts
=> refactor: add version to session endpoint

apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/stores/runtimeState.ts
fix issue where eventNex is not found if eventNow index is 0
=> fix event next

apps/client/src/common/utils/offset.ts, apps/client/src/features/app-settings/panel/feature-panel/ReportSettings.module.scss, apps/client/src/features/app-settings/panel/feature-panel/ReportSettings.tsx, apps/client/src/features/app-settings/panel/feature-panel/reportSettings.utils.ts, apps/client/src/features/overview/composite/TimeElements.module.scss, apps/client/src/features/overview/composite/TimeElements.tsx, apps/client/src/features/overview/composite/TimeLayout.module.scss, apps/client/src/features/overview/composite/TimeLayout.tsx, apps/client/src/features/rundown/entry-editor/BlockEditor.tsx, apps/client/src/features/rundown/entry-editor/composite/EventEditorImage.module.scss, apps/client/src/features/rundown/rundown-event/composite/RundownEventChip.module.scss, apps/client/src/features/rundown/rundown-milestone/RundownMilestone.tsx, apps/client/src/theme/_ontimeStyles.scss, apps/client/src/views/common/schedule/Schedule.scss, apps/client/src/views/common/schedule/ScheduleItem.tsx, apps/client/src/views/countdown/Countdown.scss, apps/client/src/views/countdown/CountdownSubscriptions.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/DurationInput.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TextLikeInput.module.scss, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TextLikeInput.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TimeInput.tsx, apps/client/src/views/studio/StudioTimers.scss
fix: prevent reflow on editing images
fix: schedule overview
fix: report on all events
refactor: over-under time colours
fix: prevent edit on delete
=> refactor: small fixes and style tweaks

apps/server/src/app.ts, apps/server/src/services/runtime-service/RuntimeService.ts, packages/types/src/definitions/runtime/RuntimeStore.ts, packages/types/src/definitions/runtime/RuntimeStore.type.ts
need to remember to remove this from the companion module
=> refactor: remove onAir

apps/server/src/api-data/custom-fields/customFields.router.ts, apps/server/src/api-data/rundown/__tests__/rundown.dao.test.ts, apps/server/src/api-data/rundown/__tests__/rundown.parser.test.ts, apps/server/src/api-data/rundown/rundown.dao.ts, apps/server/src/api-data/rundown/rundown.parser.ts, apps/server/src/api-data/rundown/rundown.service.ts, apps/server/src/api-data/rundown/rundown.types.ts, packages/types/src/definitions/core/Rundown.type.ts
the code could be better. but I am out of ideas for how to do it in a way that does not increase complexity or reduce performance
=> fix: prevent stale references to custom fields

apps/client/src/common/components/client-modal/RedirectClientModal.tsx, apps/client/src/features/app-settings/panel/network-panel/client-control/ClientControlPanel.module.scss, apps/client/src/features/app-settings/panel/network-panel/client-control/ClientList.tsx
Fixes issues mentioned in #1762
=> fix redirect issues

apps/client/src/common/utils/__tests__/rundownMetadata.test.ts, apps/client/src/common/utils/rundownMetadata.ts, apps/client/src/translation/languages/de.ts, apps/client/src/translation/languages/es.ts, apps/client/src/translation/languages/fr.ts, apps/client/src/translation/languages/it.ts, apps/client/src/translation/languages/pt.ts, apps/client/src/views/countdown/Countdown.scss, apps/client/src/views/countdown/Countdown.tsx, apps/client/src/views/countdown/CountdownSubscriptions.tsx, apps/client/src/views/countdown/SingleEventCountdown.scss, apps/client/src/views/countdown/SingleEventCountdown.tsx, apps/client/src/views/countdown/countdown.utils.ts, apps/client/src/views/countdown/useCountdownData.ts, packages/types/src/translations/index.ts
=> Countdown timeuntil

apps/client/src/common/hooks/useSocket.ts, apps/client/src/features/overview/composite/TimeElements.module.scss, apps/client/src/features/overview/composite/TimeElements.tsx, apps/client/src/features/overview/overview.utils.ts, apps/client/src/features/rundown/rundown-event/composite/RundownEventChip.tsx, apps/client/src/theme/_viewerDefs.scss, apps/client/src/views/countdown/Countdown.scss, apps/client/src/views/timeline/Timeline.module.scss, apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/restore-service/__tests__/restore.parser.test.ts, apps/server/src/services/restore-service/__tests__/restore.service.test.ts, apps/server/src/services/restore-service/restore.parser.ts, apps/server/src/services/restore-service/restore.type.ts, apps/server/src/services/runtime-service/runtime.service.ts, apps/server/src/services/timerUtils.ts, apps/server/src/stores/__mocks__/runtimeState.mocks.ts, apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/stores/runtimeState.ts, apps/server/src/utils/time.ts, e2e/tests/features/212-time-until.spec.ts, packages/types/src/definitions/runtime/RundownState.type.ts, packages/types/src/definitions/runtime/RuntimeStore.ts, packages/utils/src/date-utils/getExpectedStart.test.ts, packages/utils/src/date-utils/getExpectedStart.ts
=> Relative mode

apps/server/src/services/sheet-service/SheetService.ts, apps/server/src/services/sheet-service/sheetUtils.ts
fixes the issue where you can not export to sheets if there were groups and custom fields in the import map
=> Fix sheet export custom
