.github/workflows/build.yml
Fixing an issue where fetching yarn packages would cause network timeouts and the job to fail
=> hotfix/network: increase network timeout

apps/client/src/common/models/ViewTypes.ts, apps/client/src/features/viewers/minimal-timer/MinimalTimer.scss, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx
I've Implemented the end message in the minimal timer, following the behavior from the normal timer. If it exist's it will be shown upon passing 0. Also it is possible to disable the end message using the `?hideendmessage=true` url parameter
=> Fix: #279 End Message in Minimal Timer

.github/workflows/build.yml, server/package.json
This change should add the arm images needed for the Raspberry Pi to the automated build process
=> Add arm platforms to docker build

client/src/features/viewers/timer/Timer.jsx
`/timer?progress=up` would crash with the below error:
```
react_devtools_backend.js:2655 Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at _m (index.3fcfff09.js:30:19143)
at Fh (index.3fcfff09.js:32:12523)
at mw (index.3fcfff09.js:32:45383)
at dw (index.3fcfff09.js:32:40219)
at L_ (index.3fcfff09.js:32:40147)
at Hu (index.3fcfff09.js:32:40001)
at Hh (index.3fcfff09.js:32:36340)
at uw (index.3fcfff09.js:32:35288)
at k (index.3fcfff09.js:17:1560)
at MessagePort.Z (index.3fcfff09.js:17:1924)
```
The error decodes to
> Too many re-renders. React limits the number of renders to prevent an infinite loop.
=> Timer: fix too many renders error when using ?progress

apps/server/src/adapters/websocketAux.ts, apps/server/src/services/RundownService.ts
Broadcast ws message when the rundown changes.
So far message looks like
```
{
type: 'ontime-refetch',
payload: null,
};
```
The payload could include a patch object, but we would need to define behaviour flags for updating single/multiple items. One for the future I guess
What do you think about the name **refetch**? We will be stuck with it once we implement, not too sure it is communicative
=> feat: notify ws clients on rundown changes

apps/client/src/common/utils/__tests__/dateConfig.test.js, apps/client/src/common/utils/dateConfig.ts, apps/client/src/features/table/tableRows/BlockRow.jsx, apps/client/src/features/table/tableRows/DelayRow.jsx, e2e/tests/002-upload-showfile.spec.ts
Small improvements in the presentations of delays and blocks in cuesheet
=>  fix: cuesheet block

apps/client/src/common/components/progress-bar/ProgressBar.scss, apps/client/src/common/components/schedule/Schedule.tsx, apps/client/src/common/components/schedule/ScheduleContext.tsx, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/timer/Timer.tsx
=> style views

apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.scss, apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.tsx
Fixes an issue where the multi progress bar had classes with the same name as the progress bar, so weird stuff was happening.
Easy fix, tricky to debug
@kellhogs Can you check that I did not break anything?
=> fix: prevent css collision

apps/client/src/features/event-editor/EventEditor.tsx
closes #388 
- add `event.id` as `key` to `<EventEditorTitles />`
React will now know to re-render this component whenever the selected event changes
(I cannot reproduce this issue with `<EventEditorTimes />`, but I suspect if this bug pops up again, this fix will probably address it).
=> Fields' Stale Data Fix

apps/client/src/common/api/apiConstants.ts
apiConstants.ts currently hardcodes the websocket protocol as `ws://` which fails if the ontime page is loaded on HTTPS (as the browser rejects it as mixed content). This PR ensures `wss://` is used if the page is loaded over HTTPS.
=> Fix websocket connection behind HTTPS reverse proxy

apps/client/src/common/components/edit-form-drawer/EditFormDrawer.module.scss, apps/client/src/common/components/edit-form-drawer/EditFormDrawer.tsx, apps/client/src/common/components/edit-form-drawer/EditFormInput.tsx, apps/client/src/common/components/edit-form-drawer/constants.ts, apps/client/src/common/components/edit-form-drawer/types.ts, apps/client/src/common/components/navigation-menu/NavigationMenu.module.scss, apps/client/src/common/components/navigation-menu/NavigationMenu.tsx, apps/client/src/common/hooks/useKeyDown.ts, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/clock/Clock.tsx, apps/client/src/features/viewers/countdown/Countdown.tsx, apps/client/src/features/viewers/lower-thirds/LowerClean.jsx, apps/client/src/features/viewers/lower-thirds/LowerLines.jsx, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/public/Public.tsx, apps/client/src/features/viewers/studio/StudioClock.jsx, apps/client/src/features/viewers/timer/Timer.tsx
closes #399 
- Create `EditFormDrawer` to house the inputs. Add to `/clock` view for testing (will add to more)
- Create `EditFormInput` to handle granulated logic for interacting with search params.
- Add edit button to `NavigationMenu`. Had to adjust styles to make it possible
- Since I'll be adding `EditFormDrawer` to every clock/timer route (despite not being so DRY, which apparently isn't a concern), I simplified logic by passing the `options` prop to `EditFormDrawer`. 
- Styling is a bit difficult due to the amount of files required. I'm trying my best to emulate other `.scss` files.
I opened this PR so it's obvious this issue isn't in limbo and to serve as a source of motivation to complete this feature within a reasonable time. 
Please let me know if you think this a good step in …
=> URL Params Form

apps/client/index.html
attempt fixing issues with going fullscreen by configuring the Content Security Policy
=> fix: fullscreen permissions

apps/client/src/common/utils/copyToClipboard.ts
handle cases where navigator.clipboard can be undefined https://web.dev/async-clipboard/
=> fix: prevent clipboard error in secure context

apps/client/src/features/cuesheet/CuesheetWrapper.tsx, apps/client/src/features/cuesheet/__tests__/utils.test.js, apps/client/src/features/cuesheet/cuesheetCols.tsx, apps/client/src/features/cuesheet/cuesheetUtils.ts
Fixes issue with CSV export reported by user where the export would only contain part of the rundown.
The issue was somewhere between creating the file and the download process, so I decided to change the download process to use blobs instead.
This seems to work correctly
=> fix csv export

.github/workflows/build_v2.yml, apps/electron/package.json
Fixes #469.
Current macOS builds for Ontime only build an x64 target, which is less than ideal for Apple Silicon users. Modifies electron dist-mac script to build separate targets for aarch64 and x64 targets, and updates DMG artifactName to include target architecture.
=> dist-mac: create separate dists for aarch64, x64

apps/client/src/features/event-editor/composite/EventEditorTimes.tsx, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/viewers/common/viewerUtils.ts, apps/server/src/services/TimerService.ts, apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/timerUtils.ts, packages/types/src/definitions/TimerType.type.ts
add a feature that allows for counting to the scheduled end of an event, regardless of when it started
This attempts a more semantic way of approaching the issue described in #448
=> feat: count to end

apps/client/package.json, apps/client/src/features/event-editor/composite/CountedTextInput.tsx, apps/client/src/features/event-editor/composite/EventEditorDataLeft.tsx, apps/electron/package.json, apps/server/package.json, package.json
fixes a mistake made when adding the new cue operator, which means no text inputs allow text
=> fix: allow spaces in title input

apps/client/src/common/components/schedule/Schedule.tsx, apps/client/src/common/components/schedule/ScheduleContext.tsx, apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/viewers/ViewWrapper.tsx, apps/client/src/features/viewers/backstage/Backstage.scss, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/public/Public.tsx, apps/server/src/classes/event-loader/EventLoader.ts
small PR to add two new options to views with the scheduler component (backstage and public)
1. option to hide events that are in the past
2. option to stop the auto cycling of the schedule
=> feat: expand user options for views with schedule

apps/client/src/common/hooks/useLocalStorage.ts, apps/client/src/features/cuesheet/Cuesheet.tsx, apps/client/src/features/cuesheet/cuesheet-table-elements/CuesheetHeader.tsx, apps/client/src/features/cuesheet/cuesheet-table-settings/CuesheetTableSettings.tsx
This PR fixes issues with changes to the table header not causing re-renders:
- drag and drop to reorder columns did not work until a manual refresh of the page
- resize did not seem to work
This was likely caused by attempts to improve table performance, I hope this changes do not worsen performance significantly
=> fix: cuesheet header

apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx
Temporarily disabled the save params feature
Are you ok with this @asharonbaltazar ?
While I was doing this, it occurred to me that the presets work we spoke about might be a simpler way to solve this problem, with less potential edge cases
https://github.com/cpvalente/ontime/issues/608#issuecomment-1823473114
=> chore: disable save params feature

apps/server/src/adapters/OscAdapter.ts, apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/app.ts, apps/server/src/controllers/integrationController.ts
This PR adds the possibility for the websocket endpoint receive a change command
It achieves that by abstracting the change in the integrationController and forcing the adapters to shape the data
Closes #593
=> feat: add change endpoint to ws

apps/server/src/controllers/ontimeController.ts, apps/server/src/services/integration-service/OscIntegration.ts
Actually disable/enable osc output depending on `osc.enabledOut`
and also registers or unregisters with the IntegrationService when changing settings in the UI
so the output can now be changed without restarting.
=> Osc enabled out

apps/server/src/controllers/ontimeController.ts
fixes #647 
@alex-Arc, to test you just need to check in the app settings that the link is to the created css file not to the initial one
=> fix: correct link for CSS overrides

apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/operator/Operator.tsx
Adds user option to prevent the operator view from being editable on long press as suggested by @viktorfreiman in #609
=> refactor: prevent accidental edit in operator view

apps/client/src/features/rundown/event-block/EventBlock.module.scss, apps/client/src/features/rundown/event-block/EventBlockInner.tsx
=> fix: use background-color: transparent; for overlap indicators

apps/client/src/features/modals/upload-modal/preview/PreviewRundown.tsx, apps/client/src/features/modals/upload-modal/preview/Tag.module.scss, apps/server/src/utils/parser.ts, apps/server/src/utils/sheetUtils.ts, packages/utils/src/validate-events/validateEvent.ts
Allows importing blocks from spreadsheets, it will also skip the import of rows which contain a timer type we dont know
=> refactor: allow import of blocks and skip import

apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx
This PR makes it so that presenter displays do not show the current timer as negative when the timer is set to be a clock
Fixes #746
=> fix: timer type clock is not negative in presenter displays

apps/server/src/state.ts
this PR makes it so that an event marked as `Time-To-End` will always update as long as it is loaded
=> time to end

apps/client/src/common/api/ontimeApi.ts, apps/client/src/features/app-settings/panel/project-panel/ProjectListItem.tsx
This includes three changes:
1. Add "Download" button to the ProjectItem overflow menu.
This allows users to download the json project file for any element. 
2. Add "Export CSV Rundown" button to the currently loaded project item overflow menu.
Allowed for the currently selected item.
3. In both cases the file name is the name the user sees eg. Project 1.json or Project 1.csv
=> Project Manager: Export

apps/client/package.json, apps/client/src/features/event-editor/composite/EventEditorTimes.tsx, apps/client/src/features/rundown/event-block/composite/EventBlockTimers.tsx, apps/electron/package.json, apps/server/package.json, apps/server/src/services/__tests__/rollUtils.test.ts, apps/server/src/services/rollUtils.ts, package.json, packages/utils/src/validate-events/validateEvent.test.ts, packages/utils/src/validate-events/validateEvent.ts
Fixes #757 
It seems that the end time was larger than dayInMs and we dont expect that to happen
Unsure on how we got to this, but I have edited some parsing function to stop that from being possible
We should take a closer look at our times in v3
=> fix: issue where a end time can be overflowing

apps/client/src/features/app-settings/AppSettings.tsx, apps/client/src/features/app-settings/panel/project-settings-panel/ProjectSettingsPanel.module.scss, apps/client/src/features/app-settings/panel/project-settings-panel/ProjectSettingsPanel.tsx, apps/client/src/features/app-settings/settingsStore.ts, apps/client/src/theme/OntimeAlert.ts, apps/client/src/theme/theme.ts
Adding a simple UI so we can start working with custom fields as soon as they are ready.
The table seems excessive for now, but it gives us room to manoeuvre.
=> wip: add UI to manage custom fields

apps/server/src/stores/runtimeState.ts
testing ideas to let the end times overflow, that way we could tell the clients that an event end is the day after
however this means traversing through the rundown to find how many times we go over midnight
=> refactor: skip expected end if not playing

apps/client/src/common/context/AppContext.tsx, apps/client/src/common/hooks-query/useSettings.ts, apps/server/src/api-data/settings/settings.controller.ts, apps/server/src/classes/data-provider/DataProvider.ts, packages/utils/index.ts, packages/utils/src/generic/__tests__/generic.test.ts, packages/utils/src/generic/generic.ts
Adding some simple code to obfuscate the pincodes while in transit
any user who is capable of inspecting the network tab will also easily circumvent this. But it I guess it is a micro 
improvement and harmless (and a little fun to investigate)
Closes #755 
@alex-Arc do you think the pincode workflow needs improvements? I was a bit annoyed with having to type it everytime I refreshed the page
=> refactor: obfuscate pincode in transit

apps/client/src/features/rundown/Rundown.tsx
Recovering the code for automated following the running event.
We no longer automate navigation in edit mode, I think this makes the editing experience better
=> refactor: follow in run mode

apps/server/src/setup/index.ts
by throwing an exception there we ensure the code inside the `catch` block runs, which will then create and assign a `lastLoadedProject`
=> Fix to `lastLoadedProject` being null

apps/server/src/services/rundown-service/__tests__/rundownCacheUtils.test.ts, apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/services/rundown-service/rundownCacheUtils.ts
prevent calculating rundown 
- if the changes do not affect other events (eg. title field)
- if there are no changes in the patch object
=> Granular updates

apps/client/src/features/app-settings/panel/sources-panel/GSheetSetup.tsx, apps/client/src/features/app-settings/panel/sources-panel/SourcesPanel.module.scss, apps/server/src/services/sheet-service/SheetService.ts
catch the error that happens if you successfully authenticate but don't have permissions to the sheet and display an error in the client
also don't  block the authenticate button with a spinner 
if the user fails the auth they should be able to try again
=> fix: Sheet import

apps/client/src/features/cuesheet/cuesheet-table-elements/CuesheetHeader.tsx
Problem is we're memoizing the component, and `headerGroups` prop doesn't have the actual sizes, it is hidden behind a getter.
This means React won't think of it as an actual prop change. If we still want to memoize the component, we could pass the header sizes as a prop separately
=> Fix to cuesheet table header not resizing

apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectList.tsx, apps/client/src/features/cuesheet/CuesheetWrapper.tsx, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/overview/Overview.tsx, apps/client/src/features/rundown/Rundown.module.scss, apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/delay-block/DelayBlock.tsx, apps/client/src/features/rundown/event-block/EventBlock.tsx, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.module.scss, apps/client/src/features/rundown/quick-add-block/QuickAddBlock.tsx, apps/client/src/features/rundown/rundown-header/RundownHeader.module.scss, apps/client/src/features/rundown/rundown-header/RundownHeader.tsx, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx, apps/client/src/theme/ontimeMenu.ts, e2e/tests/000-upload-showfile.spec.ts, e2e/tests/features/203-delay-block.spec.ts, e2e/tests/features/204-editor-crud.spec.ts, e2e/tests/features/205-operator.spec.ts, e2e/tests/features/301-spreadsheet-import.spec.ts
Small tweaks from user feedback on alpha 3
@alex-Arc , what do you think of changing the text in the delay block from Apply to Make permanent?
The idea is that users seem to be confused as to what apply does. Delays do not need to be applied, this only makes them part of the schedule. Another alternative was to call it `Reschedule`, but I thought that could be even more confusing
=> V3 feedback2

apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/common/viewUtils.ts, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx, packages/utils/src/date-utils/timeFormatting.test.ts, packages/utils/src/date-utils/timeFormatting.ts
This PR fixes issues with how we display negative timers is handled in the `Timer` and `Minimal` views
=> fix: handle displaying negative timers

apps/server/src/services/TimerService.ts
I realised that we send the entire websocket payload every second
this PR makes it that we only ever send the things that change
this makes the app transmit around 8x less data. more importantly, it would allow the consumer to do less work on updating
regardless, the amount of data transmitted is very low (around 200b for a full packet) and it is arguable whether it is worth it
=> Granular ws

packages/types/.eslintrc, packages/types/src/api/ontime-controller/BackendResponse.type.ts, packages/types/src/api/rundown-controller/BackendResponse.type.ts, packages/types/src/definitions/DataModel.type.ts, packages/types/src/definitions/core/HttpSettings.type.ts, packages/types/src/definitions/core/OntimeEvent.type.ts, packages/types/src/definitions/core/OscSettings.type.ts, packages/types/src/definitions/core/Rundown.type.ts, packages/types/src/definitions/core/Settings.type.ts, packages/types/src/definitions/runtime/Runtime.type.ts, packages/types/src/definitions/runtime/RuntimeStore.type.ts, packages/types/src/definitions/runtime/TimerState.type.ts, packages/types/src/utils/guards.ts, packages/utils/.eslintrc, packages/utils/src/cue-utils/cueUtils.test.ts, packages/utils/src/cue-utils/cueUtils.ts, packages/utils/src/date-utils/timeFormatting.ts, packages/utils/src/rundown-utils/rundownUtils.test.ts, packages/utils/src/rundown-utils/rundownUtils.ts, packages/utils/src/validate-events/validateEvent.ts, packages/utils/src/validate-times/validateTimes.test.ts, packages/utils/src/validate-times/validateTimes.ts
adds `simple-import-sort/imports` and `@typescript-eslint/consistent-type-imports` to the type and utils packages
I think we will have to wait with adding it to server and client until after v3 or at least after beta
do we wan to add it for export as well?
https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how/
=> Enforece type imports

apps/server/src/services/timerUtils.ts, packages/utils/index.ts, packages/utils/src/array-utils/arrayUtils.test.ts, packages/utils/src/array-utils/arrayUtils.ts
This PR scope is to cleanup logic behind Roll
This is an important feature of Ontime I would like to improve it in the future
Currently, the feature is complex to maintain due to the fact that it can resolve a rundown out of order.
While this is nice for the user, I believe the best way forwards is to expect that the order is correct
=> refactor: rundown must be in order

apps/server/src/api-integration/integration.controller.ts, apps/server/src/api-integration/integration.utils.ts, apps/server/src/utils/parserFunctions.ts
This PR fixes the issues with the custom fields receiving an object
It seems that it was due to the removal of the nested {value: <string>} which wasnt done in the changes payload parser
It also fixes an issue where the custom fields are rebuilt on startup without forcing the key to be lower case
=> Custom fields cleanup

apps/server/src/services/integration-service/IntegrationService.ts, apps/server/src/services/runtime-service/RuntimeService.ts
Fixes the identified issue with stale data in integrations
The tradeoffs are outlined in the code
- we do not have access to data outside runtimeState (eg: messages or auxtimers)
- we couple the integrationService to runtimeState
I feel this is not ideal, but dont want to hold off the release. I think a real fix would involve some re-writing of state management and event scheduling
=> fix: state stale in integrations

apps/server/src/utils/__tests__/parserFunctions.test.ts, apps/server/src/utils/parserFunctions.ts
=> Fix: custom fields with undefined colour is not accepted by `parseCustomFields`

.github/workflows/build.yml, apps/electron/entitlements.plist, apps/electron/package.json, pnpm-lock.yaml
Signing the MacOS release of Ontime.
- Leverages electron-builder for both the signing and notarizing of the app
- `APPLE_ID` `APPLE_APP_SPECIFIC_PASSWORD` `APPLE_TEAM_ID` `CSC_KEY_PASSWORD` and `CSC_LINK` were added to the secrets and exposed in the workflow file
Question:
- I have kept the release as part of the build command, is there a reason to have a separate command? I imagined we could have an `dist-mac:local` which skips signing. This is something we can do later as users dont usually venture this far
- I did not include @electron/notarize as an explicit dependency
=> chore: sign macos dist

apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/stores/runtimeState.ts
The issue is described in #941 and #942 
Fixes #942 
It seems that we were accidentally leaving the runtime object connected to its initial reference.
I believe the fix did not introduce unintended side effects, but it would be good to have some help with sanity check
=> fix: prevent mutation of initial object

apps/server/src/config/config.ts, apps/server/src/services/TimerService.ts, apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/services/runtime-service/__tests__/rundownService.utils.test.ts, apps/server/src/services/runtime-service/rundownService.utils.ts
This PR offers a solution to improve the described in #940 
The existing implementation assumes the following:
- we update the clocks once a second, not on the turn of the second
- clock updates are considered low priority
- clock updates mentioned here are just for the WebSocket message, the integrations are checked at intervals of 32ms, apart from events such as `end` which are scheduled for extra accuracy
From previous conversations, we felt this was sufficient, but it is understandable that it may cause suspicion and loss of confidence from users side.
The proposed solution implements changes so that we have a leading update on clock and timer.
ie: we update the clock on the turn of the second, not once a second
See below the rate of updates in websocket. The clock message comes …
=> refactor: leading updates in timers

apps/server/src/stores/runtimeState.ts
Fixes an issue where the `selectedEventIndex` was not cleared on stop
Steps to reproduce:
- Clear rundown
- Make a single event
- Start event
- Stop Event
All the buttons in the playback (apart from Roll) should be disabled now
=> fix: prevent stale selection

apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/__tests__/time.test.ts, apps/server/src/utils/parser.ts, apps/server/src/utils/time.ts, packages/utils/src/date-utils/isTimeString.test.ts, packages/utils/src/date-utils/isTimeString.ts
Investigating the issues raised in #971 
This far, the issue encountered were related to unexpected data types.
I have made some small code changes and a test to support the bug report
**time warning `15` gets parsed as `0`**
in the time fields, we expect a string which is either a ISO 8601 date string or a string which includes a timestamp (eg `"09:00:00"`). In some cases the value was a number such as `15`, which was ignored by our parser
**duration `"60"` gets parsed as `0`**
the documentation suggests that the parsing of time strings is the same as the interface. this is almost correct, we first try to create a date from the string, if that fails we attempt parsing the string according to the UI rules. Unfortunately `"60"` is a valid input to the Date constructor and makes our logic …
=> fix: excel parsing

apps/client/src/features/cuesheet/CuesheetWrapper.module.scss, apps/client/src/features/editors/Editor.module.scss, apps/client/src/features/operator/Operator.module.scss, apps/client/src/index.scss
Improves the keying of the views as described in #976 
The app has two levels of background, one set at the body level, and one set at route (page) level
These are effectively the same. It seems the reason the body background was introduced was to prevent a white flash while navigating
This had the unintended consequence of complicating the keying of views.
This PR introduces some changes to improve the ease of configuration:
- use `--background-color-override` with a fallback in body
- simplify selectors in `body` to avoid issues with specificity
- set background and page level in cuesheet and editor to avoid issues with overrides
This means that we avoid the issues with flashing of background colour.
The users only need to override a single variable `--background-color-override` to see …
=> style: simplify background override

apps/client/package.json, apps/server/package.json, apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/stores/runtimeState.ts, packages/utils/package.json, pnpm-lock.yaml
It seems that we were not considering order of operations when adding time, so that the check for the finish was considering the added time twice
Also added a flag to the runtimeState to set the force the finish time. This means an `onFinish` will still trigger if the user removes time past 0
Fixes #977 
Note to reviewer: the change is very simple, but I upgraded vite so there are many lines changed (in package-lock)
You can focus just on the first commit
=> fix: handle finish when adding time

apps/client/src/features/rundown/event-block/EventBlock.utils.ts, apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/stores/runtimeState.ts, packages/utils/index.ts, packages/utils/src/date-utils/checkIsNextDay.ts
This recovers the day after indicator by fixing the out of sync logic in UI and server regarding what makes something being the day after.
It is a follow up of #952  and is discussed in #951
=> refactor: recover day after indicator

apps/client/src/common/hooks/useEventAction.ts, apps/client/src/features/control/playback/add-time/AddTime.tsx, apps/server/src/api-integration/integration.controller.ts, apps/server/src/api-integration/integration.utils.ts, apps/server/src/utils/time.ts, packages/utils/index.ts, packages/utils/src/date-utils/conversionUtils.ts, packages/utils/src/date-utils/timeFormatting.test.ts, packages/utils/src/timeConstants.ts, packages/utils/src/validate-times/validateTimes.test.ts, packages/utils/src/validate-times/validateTimes.ts
Currently, users can add whatever they want in the time fields.
eg: 1000:01:01 is totally acceptable as 1000 hours 1 minute and 1 second
This has the potential of causing issues for us, at the same time, we dont see that it brings value to users
This PR caps all timer values for a single event to 24 hours, both in the interface and using the change endpoint
Note to reviewer:
I have opted for leave the parser code untouched. This is because the logic is complex and I would like to find a good way to handle edge cases
I suggest moving time parsing improvements to another PR
=> refactor: cap timer values

apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/rundown-service/rundownCache.ts
Fixing an issue where skipped elements will still be counted for planned start and planned end
=> fix: account for skip in rundown calculations

apps/client/src/common/utils/__tests__/dateConfig.test.js, apps/client/src/common/utils/dateConfig.ts
resolve some oddities with parsing am/pm times like 10am, 12:00pm, 12:00:00am, etc. 
closes #994
=> address some issues in am/pm time parsing

apps/client/src/features/rundown/RundownExport.tsx
Proposal implementation for hiding the side bar once the rundown is extracted. Here we do this by adding a parameter to the URL #997 #989 .
This is a familiar pattern in the app, however I am not particularly happy here since it is not self documenting
ie: the user would have to know the parameter to use
I have also considered adding a toggle button, however this clutters the interface. I am not inclined to want a settings panel here as we have in cuesheet or on the views. Unsure on the best way forwards
Any ideas @alex-Ar @jwetzell @lukestein
=> refactor: allow hiding sidebar

apps/client/src/common/utils/deviceUtils.ts, apps/client/src/features/rundown/event-editor/EventEditorEmpty.tsx
- fixes an issue with wrong arrow direction in shortcuts
- fixes issues with using arrows instead of shift key
I have decided to spell out the keys rather than having symbols. I believe this makes it clearer even it it is more noisy (maybe)
@lukestein what do you think?
=> fix: correct key on shortcuts

apps/client/src/common/utils/regex.ts, apps/client/src/features/app-settings/panel/integrations-panel/OscIntegrations.tsx, apps/server/src/services/integration-service/OscIntegration.ts, apps/server/src/services/integration-service/integrationUtils.test.ts, apps/server/src/utils/__tests__/oscArgParser.test.ts, apps/server/src/utils/oscArgParser.ts, packages/types/src/definitions/core/OscSettings.type.ts, packages/utils/index.ts, packages/utils/src/regex-utils/splitWhitespace.test.ts, packages/utils/src/regex-utils/splitWhitespace.ts
This is a quick test to solve the issue described by the user
There are two points of improvement here
- we should attempt keeping the types defined by the user
- we should allow sending multiple commands
For the user defined case, where we want to send two integers `1` `1`, I believe the easiest case is to wrap this in an array  `[1,1]`, so that we can treat the arguments individually
We should take some time investigating to make sure there are no unintended side effects
Closes #953
=> refactor: improve payload type

apps/server/src/setup/index.ts
having `productionPath` and `dockerPath` is not necessary as they both resolve to the same path relative to `srcDirectory`
=> remove redundant path evaluation

apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/viewers/minimal-timer/MinimalTimer.scss, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx
Tidying up behaviour mentioned in https://github.com/cpvalente/ontime/issues/1016#issuecomment-2142585773
The overrides for `message`, `blackout` and `blink` do not apply to `/minimal`
Unfortunately this also means that we need to remove one of the parameters in the `minimal view`. 🤞
=> refactor: timer overrides do not affect minimal

apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/viewers/common/viewUtils.ts, apps/client/src/features/viewers/timer/Timer.tsx
Hello,
Its just a small patch to add an view option to enable the timer to display the full-clock instead of being hardcoded to remove leading zeros.
Let me know if i need to change or optimize things
=> Add option to display the full time (HH:mm:ss) in the timer view

apps/client/src/common/models/TimeManager.type.ts, apps/client/src/common/stores/runtime.ts, apps/client/src/declarations/declaration.d.ts, apps/client/src/features/control/playback/playback-timer/PlaybackTimer.tsx, apps/client/src/features/viewers/ViewWrapper.tsx, apps/client/src/features/viewers/minimal-timer/MinimalTimer.scss, apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.scss, apps/client/src/features/viewers/timer/Timer.tsx, apps/server/src/services/__tests__/timerUtils.test.ts, apps/server/src/services/timerUtils.ts, apps/server/src/stores/runtimeState.ts, packages/types/src/definitions/runtime/TimerState.type.ts, packages/types/src/index.ts
This PR exposes a timer phase property on the running timer.
```ts
export enum TimerPhase {
None = 'none',
Default = 'default',
Warning = 'warning',
Danger = 'danger',
Negative = 'negative',
}
```
Since we want to make the Danger and Warning thresholds events, it makes sense to calculate this in the server. Might as well expose it.
By exposing it we get the added advantage of providing better feedback to integrations.
Note to reviewer: `TimerPhase` is not a great name, suggestions are welcome
=> refactor: declare timer phase

apps/client/src/features/cuesheet/Cuesheet.tsx, apps/client/src/features/cuesheet/cuesheet-table-elements/CuesheetHeader.tsx, apps/client/src/features/cuesheet/cuesheet-table-elements/EventRow.tsx, apps/client/src/features/cuesheet/cuesheet-table-settings/CuesheetTableSettings.tsx, apps/client/src/features/cuesheet/store/CuesheetSettings.tsx
closes #899
This PR adds an option to toggle the visibility of the index column:
https://github.com/cpvalente/ontime/assets/58940073/db306797-df4e-4eb7-ab3a-ba52487ed1f5
This approach doesn't use React Table's toggling implementation due to the difficulty of calculating the `eventIndex`. 
The `eventIndex` is incremented upon render and skips delaying or blocking blocks, making it hard to calculate the _ontime event index_ sum in the `cell` property when instantiating columns. I think to circumvent this we'd have to return `BlockRow`/`DelayRow` within each `cell`. 
Therefore, I've extended the existing `CuesheetSettings` store (which I see enables functionality outside of React Table's "control") to manage the toggle state
Would love to hear alternative approaches 👀
=> feat:toggle index column

apps/client/src/features/viewers/minimal-timer/MinimalTimer.tsx, apps/client/src/features/viewers/timer/Timer.tsx
When a timer is marked as count-up I believe it makes no sense to show the warning, danger times and negative times modifier since we made we made a choice to hide this from the user
This PR changes the minimal and timer views to make sure that count-up timers dont have the colour modifiers
@lukestein what do you think?
=> refactor: supress modifiers in count-up timers

apps/client/src/features/operator/Operator.tsx
The operator view had some different logic for loading the main field that did not consider custom fields. I have aligned the main field population with the secondary field. If this is not the desired behavior then a solution that handles custom fields should be proposed.
Closes #1047
=> consider custom fields when loading operator main field

apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.scss, apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.tsx, apps/client/src/features/cuesheet/cuesheet-progress/CuesheetProgress.tsx, apps/client/src/features/operator/status-bar/StatusBar.module.scss, apps/client/src/features/operator/status-bar/StatusBarProgress.tsx
**this is a fix for #900**
Hey, new user here really enjoying the app! I saw this issue was very similar to something I ran into recently, so throwing in this potential solution. As I understand it this has to do with sub-pixel rendering issues in the browser when using `overflow: hidden` to clip corners, where multiple elements being clipped always come out slightly differently due to anti-aliasing.
I reworked the HTML a little bit so that the colored backgrounds don't overlap, which solves most of this. But the indicator has to overlap with them to work, so I made it match the background color and go 1px beyond the edge of the status bar. This works, but should be noted it would look terrible on any other background color unless the component was fed the new background color as well. …
=> fix for MultiPartProgressBar styling

DEVELOPMENT.md, apps/electron/main.js, apps/electron/package.json, apps/server/src/app.ts, apps/server/src/classes/Logger.ts, apps/server/src/index.ts, apps/server/src/utils/console.ts, packages/types/src/definitions/runtime/Logger.type.ts, turbo.json
since so many users are consuming Ontime headless, I thought we should look into improving the visibility of messages in terminal
In this PR I am just adding visibility for critical operations
- where is ontime running
- did ontime crash
TODO:
Suggestions for improvement are welcome
=> refactor: improve console visibility

apps/server/src/utils/__tests__/coerceType.test.ts, apps/server/src/utils/coerceType.ts
Allow the api to set the event colour to '' by calling 'none'
Otherwise there is no way for the api to match the UI button
=> None colour from API

apps/client/src/features/cuesheet/Cuesheet.module.scss, apps/client/src/features/cuesheet/Cuesheet.tsx, apps/client/src/features/cuesheet/cuesheetCols.tsx, apps/client/src/features/cuesheet/useColumnManager.tsx
small fixes to the ordering and visibility of columns in the cuesheet
Testing:
You should be able to reorder columns. Leave the page and come back and everything looks the same
=> refactor: cuesheet header

apps/client/src/features/app-settings/panel/project-panel/ProjectForm.tsx, apps/client/src/features/app-settings/panel/project-panel/ProjectListItem.tsx, apps/server/package.json, apps/server/src/app.ts, apps/server/src/classes/Logger.ts, apps/server/src/index.ts, apps/server/src/setup/index.ts, apps/server/src/utils/console.ts, apps/server/src/utils/generateCrashReport.ts, apps/server/src/utils/upload.ts, packages/utils/package.json, pnpm-lock.yaml
Extracted some small changes from the corrupted files PR
=> Refactor load

.github/workflows/build_cli.yml, .github/workflows/build_docker.yml
- published type is any published release (pre-release/latest)
- the release [object](https://docs.github.com/en/webhooks/webhook-events-and-payloads#release) includes the tag name so no need to extract it anymore
Closes #1107
=> switch workflows to release trigger

apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/stores/runtimeState.ts
Ensure that we emit the load event on reload, as discussed in #1119
=> refactor: emit load event on reload

apps/server/src/api-data/rundown/rundown.controller.ts, apps/server/src/api-data/rundown/rundown.router.ts, apps/server/src/api-data/rundown/rundown.validation.ts, apps/server/src/services/rundown-service/RundownService.ts, apps/server/src/services/rundown-service/__tests__/rundownUtils.test.ts, apps/server/src/services/rundown-service/rundownUtils.ts, apps/server/src/services/runtime-service/RuntimeService.ts, packages/types/src/api/ontime-controller/BackendResponse.type.ts, packages/types/src/index.ts
This PR exposes the list of changes in the refetch message.
This means that consumers can know which events are affected by a change
In addition, we also add a few endpoints for granular rundown getting
- paginated query params for rundown
- getEventById
=> Rundown api

Dockerfile
Seems to be some [known issue](https://github.com/nodejs/docker-node/issues/1946) with alpine images and node >= 20 this is breaking the docker builder stage. This switches the builder stage to a debian based node image. I have tested this is working now with multi-platform builds.
=> switch Dockerfile build stage to non-alpine image

.github/workflows/build_docker.yml
- arm/v6 and arm/v7 should be software compatible so there shouldn't be less support for devices out there with this change
=> drop arm/v6 image

Dockerfile, docker-compose.yml
as discussed this is a "breaking" change and these changes will need to be reflected in the [ontime-docs](https://github.com/cpvalente/ontime-docs) repo.
I tested an example "transition" setup and simply converting the volume mount(s) from `/external/...` to `/data/...` worked just fine although I would always preface these kinds of things with "make sure you have a backup of your data..."
=> update Docker data directory to /data

apps/server/src/stores/__tests__/runtimeState.test.ts
test failing in github actions
=> test failing

apps/client/src/features/viewers/timeline/TimelinePage.tsx
seems that we were using the wrong dataset in the timeline view, meaning that no backstage events were available
=> fix: use unfiltered events in timeline

apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/stores/runtimeState.ts, packages/utils/src/rundown-utils/rundownUtils.ts
This is a suggestion for how to reset state when block loading
The idea being, that the consumer function is the one that contains the context as to why we need to persist after clear, so it makes sense to leave this knowledge there
Otherwise, the logic hasnt been changed
I have also noticed that in the UI, the time in block starts on -1, I am assuming this is likely an issue with the `block.startedAt` and `clock` being out of sync for an update.
We should do something to prevent this as a negative value is not valid in this context
=> Suggestion

apps/server/src/services/rundown-service/RundownService.ts, apps/server/src/services/runtime-service/RuntimeService.ts
The code changes make it so that only functions that are exposed to be externally consumed broadcast their result
This means cleaner outputs in compound functions like `startNext` and `loadNext`
=> refactor: only broadcast public

apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/stores/runtimeState.ts
TimerPahse when loading and reloading from a playing event is different
uses the same function path for load and reload
optionally, also renamed runtimeState functions to better reflect their use, but this could be rolled back
`runtimeState.reload` -> `runtimeState.updateLoaded`   (maybe refresh is better?)
`runtimeState.reloadAll` -> `runtimeState.updateAll`
=> fix TimerPahse difference from load and reload

apps/client/src/features/viewers/studio/StudioClock.scss, apps/client/src/features/viewers/studio/StudioClock.tsx, apps/client/src/features/viewers/studio/StudioClockSchedule.tsx, apps/client/src/features/viewers/studio/__tests__/studioClock.utils.test.ts, apps/client/src/features/viewers/studio/studioClock.options.ts, apps/client/src/features/viewers/studio/studioClock.utils.ts, packages/utils/index.ts, packages/utils/src/date-utils/conversionUtils.test.ts, packages/utils/src/date-utils/conversionUtils.ts
Adds option to disable right section in studio clock so we only get the clock view in the center
As described in #1168
=> refactor: add options to hide schedule

apps/server/src/services/__tests__/rollUtils.test.ts, apps/server/src/services/rollUtils.ts, apps/server/src/stores/runtimeState.ts
Fixes an issue where we would fail to recognise if a rundown had multiple days
This was because of the naive evaluation of `wrapsAroundMidnight = firstEvent.timeStart > lastEvent.timeEnd`
I believe the best (ie: easiest and safest) fix is to try and be less clever, and force the loader to always iterate through the dataset. This at cost of performance and some complexity
=> fix: issue with roll evaluating multiple days

apps/client/src/common/hooks/useSocket.ts, apps/client/src/features/viewers/timeline/Timeline.tsx, apps/client/src/features/viewers/timeline/TimelinePage.tsx, apps/client/src/features/viewers/timeline/timeline.utils.ts, packages/types/src/utils/guards.ts, packages/utils/src/date-utils/checkIsNextDay.test.ts, packages/utils/src/date-utils/checkIsNextDay.ts
Still some work to be done here, this PR introduces first batch of improvements to the timeline
- Show correct upcoming events
- Refresh page if options change
- handle timeline with multiple days
- handle filtering events from timeline
=> fix: handle multiple days

apps/client/src/common/hooks/useEventAction.ts, apps/client/src/common/stores/editorSettings.ts, apps/client/src/features/app-settings/panel/interface-panel/EditorSettingsForm.tsx
Implements improvements as suggested in #1167
=> refactor: enable timer type and end action default settings

apps/server/src/services/integration-service/OscIntegration.ts
Looks like we were sending the OSC messages even if the output was disabled.
This is a one liner to correct this
=> fix: stop integration if output disabled

apps/client/src/common/components/navigation-menu/NavigationMenu.module.scss, apps/client/src/common/components/navigation-menu/NavigationMenu.tsx, apps/client/src/viewerConfig.ts
As discussed, this change makes that the navigation menu links will open in a browser window if the user is in electron
=> feat: electron links open in browser

apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/stores/runtimeState.ts
Looks like we have a bug where, if we start the timer, and change a property of the next event, The `eventNext` object in the server state does not get updated
this is a one liner to fix it
=> fix: issue where event next was stale

apps/client/src/common/hooks/useSocket.ts, apps/client/src/common/stores/runtime.ts, apps/client/src/features/app-settings/panel/general-panel/ViewSettingsForm.tsx, apps/client/src/features/control/message/InputRow.tsx, apps/client/src/features/control/message/MessageControl.module.scss, apps/client/src/features/control/message/MessageControl.tsx, apps/client/src/features/control/message/MessageControlExport.jsx, apps/client/src/features/control/message/TimerPreview.tsx, apps/client/src/features/control/message/TimerViewControl.tsx, apps/client/src/features/control/playback/aux-timer/AuxTimer.tsx, apps/client/src/features/editors/Editor.module.scss, apps/client/src/features/editors/EditorMixin.scss, apps/client/src/features/rundown/event-block/EventBlockInner.tsx, apps/client/src/features/viewers/ViewWrapper.tsx, apps/client/src/features/viewers/timer/Timer.scss, apps/client/src/features/viewers/timer/Timer.tsx, apps/client/src/theme/_viewerDefs.scss, apps/server/src/api-integration/__tests__/integration.legacy.test.ts, apps/server/src/api-integration/integration.controller.ts, apps/server/src/api-integration/integration.legacy.ts, apps/server/src/app.ts, apps/server/src/services/message-service/MessageService.ts, apps/server/src/services/message-service/__tests__/MessageService.test.ts, apps/server/src/services/message-service/__tests__/messageUtils.test.ts, apps/server/src/services/message-service/messageUtils.ts, e2e/tests/features/201-message-control.spec.ts, packages/types/src/definitions/runtime/MessageControl.type.ts, packages/types/src/index.ts, packages/types/src/utils/utils.type.ts
WIP
The idea is to help users manage the timer view and make things friendlier
https://www.figma.com/design/TOjSQ4e8q4dhNDNN5DElD3/ontime?node-id=1722-6&t=9OAa5afIUFi2Ule1-1
This also helps resolve #1024 
- expose button to show auxiliary as secondary
- expose button to show external as secondary (previously disabled)
- create preview of timer
- show timer type with tooltips in preview
- show timer phase (warning / danger) in preview
Questions:
The button for external visibility is duplicated, I experimented without it but it felt strange to have two different inputs for External Message and Timer Message. I am not sure what the best way is here
I opted for not showing the real message and time to be conservative of performance. While this is a nice feature, I didnt feel it was worth the …
=> feat: timer preview

apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/parser.ts, apps/server/src/utils/parserUtils.ts
add trim to the `makeString` parser utility functions
and use it for timer type
=> handle timer type whitespace in sheet import

apps/client/src/features/control/message/TimerPreview.tsx
When the timer is negative, the message preview was inheriting the overtime styles
This is a one liner to correct the issue
=> refactor: message does not have negative style

apps/client/src/common/utils/__tests__/regex.test.ts, apps/client/src/common/utils/regex.ts, apps/client/src/features/app-settings/panel/integrations-panel/HttpIntegrations.tsx, apps/server/src/utils/__tests__/parserFunctions.test.ts, apps/server/src/utils/parserFunctions.ts
We have got a user report that they need the HTTP integration to allow a target that who is not behind an HTTP protocol
In the user example, we would like to have `kmtrigger://macro=...`
Our development policy is often to not interfere with users setup as long as we can make it safe in Ontime.
In this case, I am unsure if we can get into trouble by being too permissive with the HTTP target
I couldn't find any reason for issues other than https requests will be rejected, https://httpwg.org/specs/rfc9110.html#field.host
Any ideas @alex-Arc or @jwetzell? Is there maybe another type of validation we should be doing?
=> refactor: allow messages not starting with http

apps/server/src/api-integration/integration.controller.ts, apps/server/src/app.ts, apps/server/src/classes/simple-timer/SimpleTimer.ts, apps/server/src/classes/simple-timer/__tests__/SimpleTimer.test.ts, apps/server/src/config/config.ts, apps/server/src/services/aux-timer-service/AuxTimerService.ts
Small improvements to the aux input
=> refactor: allow aux change direction while playing

apps/client/src/features/app-settings/panel/feature-settings-panel/UrlPresetsForm.tsx, apps/client/src/features/app-settings/panel/integrations-panel/HttpIntegrations.tsx, apps/client/src/features/app-settings/panel/integrations-panel/OscIntegrations.tsx, e2e/tests/features/206-url-preset.spec.ts
user feedback: when adding new integrations or URL, they forget to activate it and wonder why it doesnt work
=> refactor: items active by default

apps/client/src/externals.ts, apps/client/src/features/app-settings/panel/feature-settings-panel/FeatureSettings.module.scss, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldEntry.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldForm.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFields.tsx, apps/client/src/theme/OntimeAlert.ts, apps/server/src/api-data/custom-fields/customFields.validation.ts, apps/server/src/services/integration-service/OscIntegration.ts, apps/server/src/services/rundown-service/__tests__/rundownCache.test.ts, apps/server/src/services/rundown-service/rundownCache.ts, apps/server/src/utils/__tests__/parserFunctions.test.ts, apps/server/src/utils/parserFunctions.ts, packages/utils/index.ts, packages/utils/src/customField-utils/customFieldLabelToKey.ts, packages/utils/src/regex-utils/isAlphanumeric.ts
- removes the lower casing of custom fields
- doesn't allow duplicate custom fields from CustomFieldForm
=> make custom fields case sensitive

apps/electron/src/menu/applicationMenu.js
As noted I still contend this is a bug with electron. I still haven't found a single app where pressing`ctrl` plus the key that `+` is on does not zoom in. 
Closes #1256
=> add more shortcuts for zooming in

apps/client/src/common/hooks/useEventAction.ts, apps/client/src/common/stores/editorSettings.ts, apps/client/src/features/app-settings/panel/interface-panel/EditorSettingsForm.tsx, apps/client/src/features/rundown/time-input-flow/TimeInputFlow.tsx
improving UX around lock times
=> improving UX around lock times

apps/client/src/features/viewers/lower-thirds/lowerThird.options.ts, apps/client/src/features/viewers/public/public.options.ts, apps/client/src/features/viewers/timer/timer.options.ts
Ensuring that notes can be used as a data source in all views
As mentioned in #1251
=> refactor: notes as data source

apps/client/src/features/app-settings/panel/sources-panel/import-map/ImportMapForm.tsx, apps/client/src/features/app-settings/panel/sources-panel/import-map/importMapUtils.ts, apps/client/src/features/app-settings/panel/sources-panel/preview/PreviewRundown.tsx, apps/server/package.json, apps/server/src/api-data/excel/excel.service.ts, apps/server/src/services/sheet-service/SheetService.ts, apps/server/src/utils/__tests__/parser.test.ts, apps/server/src/utils/parser.ts, pnpm-lock.yaml
- switch from `node-xlsx` to `xlsx`
- evaluate excel formulars functions
- allow space and upper case in custom import
=> Improve xlsx import

apps/client/package.json, apps/client/src/features/editors/Editor.tsx, apps/client/src/features/editors/finder/Finder.module.scss, apps/client/src/features/editors/finder/Finder.tsx, apps/client/src/features/editors/finder/useFinder.tsx, apps/client/src/features/rundown/event-editor/EventEditorEmpty.tsx, apps/client/src/theme/ontimeModal.ts, pnpm-lock.yaml
feature to pair up with reporter.
It provides an interface for searching an event in the rundown
I guess this could be easily extendable to have a list of settings shortcuts like network view settings
With the current setup this would mean typing `settings network`or `settings view`.
Perhaps we would prefer having a character to signify our tags? like `>cue` or `>settings`?
We will be a bit stuck with whatever we decide now
=> feat: event finder

apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldForm.tsx
This PR fixes an issue described in #1305. 
In the custom fields form we attempted validating the uniqueness of keys in edit mode.
This means it always failed since the thing under edit was equal to something that exists
=> fix: allow changing custom field colour

apps/client/src/common/components/view-params-editor/ParamInput.tsx, apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx, apps/client/src/features/operator/Operator.tsx
A few issues here
- if a custom field contained upper case letters, the subscription did not work
- if a custom field contained spaces, it would break the parsing of multiple fields
- adding a chevron to the menu to symbolise that the item is a combobox
=> fix: custom fields subscription

apps/client/src/common/components/navigation-menu/FloatingNavigation.tsx, apps/client/src/common/components/navigation-menu/NavigationMenu.module.scss, apps/client/src/common/components/navigation-menu/ViewLockedIcon.tsx, apps/client/src/common/components/navigation-menu/ViewNavigationMenu.tsx, apps/client/src/common/hooks/useFadeOutOnInactivity.tsx
I attempted to lock navigation with `useBlocker`, but there are two roadblocks to implement this feature:
- the `react-router-dom` package needs an upgrade. I was able to do so without any problems, FYI
- the hook is a data hook and thus only works with the `RouterProvider` configuration, which means re-doing `AppRouter.tsx` to use `createBrowserRouter`
=> feat(ui): disable menu buttons with `locked` param

apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/RundownEntry.tsx
fixes an issue where using the `QuickAddBlock` to add a `Block` or `Delay`, would do so after the last event, not before the selected element
=> fix: previous eventid is any entry

apps/server/src/services/integration-service/OscIntegration.ts
Fix error where the OSC RX and TX when shutdown closed the wrong counterpart
also moved the log statements so it only logs if there is something to close
=> OSC tx and RX shutdown was swapped

apps/client/src/features/editors/finder/useFinder.tsx
This PR fixes an issue where the finder would keep the previous filtering results even if the data set changed
=> fix: prevent stale data in finder

apps/client/src/features/control/playback/playback-timer/PlaybackTimer.tsx, apps/server/src/config/config.ts, apps/server/src/services/runtime-service/RuntimeService.ts
it seems that we were passing to the calculation, the time the last integration was fired, rather than the last update
this meant that the skip threshold (1000ms) was potentially higher than the update rate (>1000ms) and could cause issues
This is mostly a patch and maybe not the best fix. However, I couldnt think of a fix here other than guaranteeing that the `skipLimit` must be higher than the clock `updateRate`
Also made a quick change to the time added tooltip to avoid showing like "added 946 seconds"
=> fix: rolling over midnight wrongly classified as skip

apps/server/src/api-integration/integration.controller.ts, apps/server/src/services/aux-timer-service/AuxTimerService.ts
exposes an endpoint for adding time to the aux timer. as described in #1356
=> feat: allow add time to aux timer

apps/client/src/common/stores/runtime.ts, apps/client/src/common/utils/socket.ts
this PR uses the websocket connection to maintain a flag that indicates whether the user is online
I have decided to reuse the ping property here and simply make it negative to indicate an offline state
=> refactor: maintain an isOnline flag in client

apps/electron/src/menu/applicationMenu.js
fixes the issue with some shortcuts not working in macOS as reported in #1376
=> fix: recover edit menu and shortcuts

apps/client/src/common/components/view-params-editor/ViewParamsEditor.module.scss, apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx, apps/client/src/theme/_ontimeStyles.scss
Users enable their own custom CSS to style the views. Making any changes to views from the settings will potentially clash with their custom CSS settings. This PR adds a warning before saving their settings.
=> feat(ui): add warning in view params when styles are overriden

apps/client/src/features/overview/Overview.module.scss, apps/client/src/features/overview/Overview.tsx
adding some simple styles for an offline indicator
dashboard has opacity and we show a small label in the bottom right corner
=> feat: create offline indicator

apps/client/src/common/components/input/text-input/useReactiveTextInput.tsx, apps/client/src/common/components/input/time-input/TimeInput.tsx, apps/client/src/common/hooks/useEventAction.ts, apps/client/src/declarations/declaration.d.ts, apps/client/src/features/rundown/time-input-flow/TimeInputFlow.tsx, apps/client/src/theme/ontimeTextInputs.ts, apps/client/src/views/cuesheet/CuesheetPage.tsx, apps/client/src/views/cuesheet/cuesheet-table/CuesheetTable.module.scss, apps/client/src/views/cuesheet/cuesheet-table/CuesheetTable.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/CuesheetHeader.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/EventRow.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/MultiLineCell.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/SingleLineCell.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TextLikeInput.module.scss, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TextLikeInput.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/TimeInputDuration.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/cuesheetCols.tsx, apps/client/src/views/cuesheet/cuesheet.options.ts, packages/types/src/definitions/core/OntimeEvent.type.ts, packages/types/src/index.ts
This PR allows editing duration in the cuesheet.
Once we are happy with the experience of this element, I will create a second PR that applies the same changes to the start and end times
The new implementation introduces a new Element `TextLikeInput` which handles the switch between a piece of text and an input
This will allow us to have different presentation and input elements and simplify things going forward
Also in the same change, we introduce a new flag to the time update function which allows locking the time strategy on update. This is to make the time input in the cuesheet simpler, without needing to use the lock icons and buttons
it also makes a few tweaks to the styles of the cuesheet
most significant:
- extract action button to visually outside the table (the idea is to be …
=> Cuesheet times

apps/server/src/app.ts, apps/server/src/services/message-service/MessageService.ts, apps/server/src/services/message-service/__tests__/MessageService.test.ts, apps/server/src/stores/EventStore.ts
we are having some race conditions issues between the initialisation of the store and the message service.
This is a small PR to solve this
The problem is exposed in the integrations PR
=> refactor: prevent race conditions on init

apps/client/src/common/components/input/colour-input/Swatch.tsx, apps/client/src/common/components/input/colour-input/SwatchPicker.tsx, apps/client/src/common/components/input/colour-input/SwatchSelect.module.scss, apps/client/src/common/components/input/popover-picker/PopoverPicker.module.scss, apps/client/src/common/components/input/popover-picker/PopoverPicker.tsx, apps/client/src/features/app-settings/panel/general-panel/ViewSettingsForm.tsx
I was chasing some issues with the border-radius in the colour picker and realised that there was one more implementation I didnt see before
This PR did not manage to cleanup the issue with the styles (although it seems straightforward [in the sandbox provided by the library](https://codesandbox.io/p/sandbox/react-colorful-customization-demo-mq85z))
However I did try and cleanup the implementations to (hopefully) better distribute the abstractions
- popover picker doesnt need to receive an icon, since the icon is an element of the picker, we could also simplify the element composition and remove some DOM elements
- the hover styles didnt seem to work
- we had separate (and conflicting) styles to the swatch element which have now been unified
- remove some unused and duplicated code and …
=> refactor: cleanup picker implementations

apps/client/src/features/app-settings/panel/client-control-panel/ClientList.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/UrlPresetsForm.tsx
the client path column can look broken if there is only one client
the easiest fix is to always show the path so the table does not change
Also added a small change to prevent users from testing URL presets which havent been saved (and wont work)
=> tweaks to forms

apps/server/src/services/rundown-service/rundownCacheUtils.ts
small PR to add `countToEnd` to the whitelist of properties that do not invalidate the rundown
thank you for bringing this up @alex-Arc
=> refactor: countToEnd does not cause rundown recalculation

apps/server/src/api-data/sheets/sheets.validation.ts, e2e/tests/000-upload-showfile.spec.ts
users seems to be getting errors with the validation, in the example we got, the sheetId had 33 characters
This PR makes the validation accept ids between 20 and 100 characters
=> refactor: wider sheet id length

apps/spec/automations.md
extracting documentation from the automation PR
=> chore: write feature spec

apps/client/package.json, apps/client/src/App.tsx, apps/client/src/features/viewers/backstage/Backstage.tsx, apps/client/src/features/viewers/public/Public.tsx, apps/client/src/features/viewers/timer/Timer.tsx, pnpm-lock.yaml
replace `framer-motion` with `motion` and load as little as possible
[Reduce bundle size](https://motion.dev/docs/react-reduce-bundle-size)
takes us from 334.81kb to 215.79kb
might be able to do more but unsure how
=> Replace framer

Dockerfile, apps/client/src/common/utils/urlPresets.ts, apps/server/package.json, apps/server/src/adapters/WebsocketAdapter.ts, apps/server/src/app.ts, apps/server/src/externals.ts, apps/server/src/html/login.html, apps/server/src/middleware/authenticate.ts, apps/server/src/middleware/noop.ts, apps/server/src/setup/index.ts, apps/server/src/utils/hash.ts, pnpm-lock.yaml
This is a proposal for protecting the HTTP connections with a password
Strategy
- requests go through authentication middleware
- if the password is active and the user has not provided a password in the cookie or params
- a) for the client assets, we serve a login page instead
- b) for the data endpoints, we refuse the request
- when the user sets the correct password in the login form, we set the cookie that will be with all requests
Notes:
- had to do some cheating to allow the client to access public files, which are requested before the connection is made
- need to test the token in query params solution, do we want UI to generate this? or pass the password in the websocket request? The token in query params will be important for generating an authenticated URL and for the companion …
=> feat: add simple auth to server requests

apps/client/src/AppRouter.tsx, apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.scss, apps/client/src/common/components/multi-part-progress-bar/MultiPartProgressBar.tsx, apps/client/src/common/components/title-card/TitleCard.scss, apps/client/src/common/components/title-card/TitleCard.tsx, apps/client/src/features/operator/status-bar/StatusBar.module.scss, apps/client/src/features/viewers/common/superscript-time/SuperscriptTime.scss, apps/client/src/features/viewers/common/superscript-time/SuperscriptTime.tsx, apps/client/src/features/viewers/common/viewUtils.ts, apps/client/src/theme/_viewerDefs.scss, apps/client/src/views/cuesheet/cuesheet.options.ts, apps/client/src/views/timer/Timer.scss, apps/client/src/views/timer/Timer.tsx, apps/client/src/views/timer/timer.animations.ts, apps/client/src/views/timer/timer.options.ts, apps/client/src/views/timer/timer.utils.ts, apps/server/src/user/styles/override.css, packages/utils/src/validate-events/validateEvent.test.ts
Starting the design review with the timer and associated components. This is divided in two parts
Style and code tweaks
Behaviour and structure changes
=> design review: timer

apps/client/src/common/stores/runtime.ts, apps/client/src/common/utils/socket.ts, apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/services/runtime-service/rundownService.utils.ts, apps/server/src/stores/EventStore.ts, apps/server/src/stores/runtimeState.ts
- add batching to the client `runtime.ts`
- rearrange and explain the update logic `RuntimeService.ts`
- fix some strict stuff in `RuntimeService.ts`
- fix a issue where the paused state was not properly applied from a restore point in `runtimeState.ts`
=> More batch

apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/stores/runtimeState.ts
I was looking into an issue where roll mode would not set the time in block
It seems to me that our existing logic is incorrect, and that we wanted to be setting the time when our conditions matched (blocked changed)
@alex-Arc , can you please sanity check this?
I may have missed something
=> fix: update time in block

apps/client/src/common/components/view-params-editor/ParamInput.tsx, apps/client/src/features/app-settings/panel-utils/PanelUtils.module.scss, apps/client/src/features/app-settings/panel/automations-panel/AutomationForm.tsx
Fixes issue with not being able to scroll the menulist if there are many elements
=> refactor: handle overflow in menulist

apps/client/src/features/app-settings/panel/automations-panel/AutomationForm.tsx, apps/client/src/features/app-settings/panel/automations-panel/template-input/TemplateInput.module.scss, apps/client/src/features/app-settings/panel/automations-panel/template-input/TemplateInput.tsx, apps/client/src/features/app-settings/panel/automations-panel/template-input/__tests__/templateInput.utils.test.ts, apps/client/src/features/app-settings/panel/automations-panel/template-input/templateInput.utils.ts, apps/server/src/stores/runtimeState.ts, packages/types/src/definitions/runtime/RuntimeStore.ts
this adds autocomplete for templates in the osc arguments
=> feat: add autocomplete to osc arguments

apps/client/src/common/components/buttons/IconButton.module.scss, apps/client/src/common/components/buttons/IconButton.tsx, apps/client/src/views/cuesheet/cuesheet-table/CuesheetTable.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/EventRow.tsx
Before we continue adding features into the cuesheet, we needed to gain some performance budget
This code changes the mostly the row composition and replaces the chakra button with a native button
The initial render is about 2x faster while sequential updates are like 8x faster
=> Improve cuesheet performance

apps/client/src/common/components/view-params-editor/__tests__/constants.test.ts, apps/client/src/common/components/view-params-editor/constants.ts, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldEntry.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFieldForm.tsx, apps/client/src/features/app-settings/panel/feature-settings-panel/custom-fields/CustomFields.tsx, apps/client/src/features/rundown/event-editor/EventEditor.module.scss, apps/client/src/features/rundown/event-editor/EventEditor.tsx, apps/client/src/features/rundown/event-editor/composite/EventEditorImage.module.scss, apps/client/src/features/rundown/event-editor/composite/EventEditorImage.tsx, apps/client/src/features/rundown/event-editor/composite/EventTextInput.tsx, apps/client/src/theme/_ontimeColours.scss, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/EditableImage.module.scss, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/EditableImage.tsx, apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/cuesheetCols.tsx, apps/server/src/api-data/custom-fields/customFields.validation.ts, apps/server/src/utils/__tests__/parserFunctions.test.ts, apps/server/src/utils/parserFunctions.ts, packages/types/src/definitions/core/CustomFields.type.ts
This is a proof of concept for allowing users to add images in a special custom field type
The code should follow the current work in the cuesheet in #1483 
> Either way, there are still some decisions to be made
> - is it sufficient that the user gives us image links?
> - how about users leveraging ontime offline?
> - We could have a combined flow where users could upload a file or give us the link, what would happen to the file transfer flow?
> - what should happen in the operator view?
> - what should happen in all the views that consume images as a secondarySource?
We have decided to go with a simple implementation that only receives images as external URLs
Users should be able to consume and change this images in the editor and cuesheet
To answer the questions above:
>- is it …
=> feat: add custom field type of image

apps/cli/package.json, apps/client/package.json, apps/electron/package.json, apps/server/package.json, package.json
Release notes:
This release introduces two major features to Ontime
- Relative offset mode: allows modifying the offset calculations depending on whether the rundown start time is significant
- Event automation: allows adding automations at the event level
There are also some smaller features and fixes worth noting:
- Allow editing CSS override in the settings
- Improve usability of lower thirds with addition of separate in, out and hold timings 
- fix issue with studio clock timer size
- fix issue with delays disappearing when editing an event
=> bump version to 3.15.0

apps/server/src/services/project-service/ProjectService.ts, apps/server/src/utils/__tests__/fileManagement.test.ts, apps/server/src/utils/fileManagement.ts
every project load was causing a renumber so I
moved the `generateUniqueFileName` logic from the ´loadProject´ function to the `createProject` function
and changed the deafult / new show funtions to use `create` instead of `load`
=> Fix project renumber

apps/client/src/views/cuesheet/__tests__/cuesheet.utils.test.ts, apps/client/src/views/cuesheet/cuesheet.utils.ts, apps/server/src/utils/parser.ts
addresses #1310
- exported type under Type column on frontend
- added a condition to check if `maybeTimeType` is equal to 'event' (without this, the flow falls into the else block where none of the events get imported, only the blocks get imported)
- CSV export
- Excel
- Preview during importing excel
=> refactor: block event xlsx import

apps/client/src/common/utils/time.ts, apps/client/src/features/viewers/common/viewUtils.ts, apps/server/src/services/runtime-service/RuntimeService.ts, apps/server/src/services/runtime-service/rundownService.utils.ts, e2e/tests/features/212-time-until.spec.ts, packages/utils/index.ts, packages/utils/src/date-utils/conversionUtils.test.ts, packages/utils/src/date-utils/conversionUtils.ts, packages/utils/src/date-utils/timeFormatting.test.ts, packages/utils/src/date-utils/timeFormatting.ts
The goal of this PR is to change the millis to seconds so that it rounds differently depending on it counting up or down
when counting down we round up so that the value will change at the exact point that the value is correct
and the opposite when counting up
also looks to help a bit with the wall clock skipping seconds sometimes
=> Refactor: better rounding

apps/client/src/features/app-settings/panel/general-panel/StyleEditorModal.module.scss, apps/client/src/features/app-settings/panel/general-panel/ViewSettingsForm.tsx, apps/client/src/theme/ontimeModal.ts
Modified the base styling of the Info component (`Info.module.scss`) to ensure it aligns to the left within its parent container. This is achieved by setting `width: fit-content;` and `align-self: flex-start;` on the component's main class.
Removed the temporary `infoLeftAligned` class from `StyleEditorModal.module.scss` and its usage in `StyleEditorModal.tsx` as the base component now handles its own left alignment correctly.
This addresses your feedback to make the component itself left-aligned, rather than just its text content via a specific override class.
=> Refactor: Align Info component to the left by default

DEVELOPMENT.md, turbo.json
Updated DEVELOPMENT.MD to use `turbo run <task>` instead of `turbo <task>` for clarity and consistency when referring to Turborepo tasks that don't have a direct pnpm script alias.
Also, added `dependsOn: ["build"]` to `dist-*` tasks in `turbo.json` to ensure correct build order before packaging.
=> Docs: Update DEVELOPMENT.MD with explicit turbo run commands

apps/client/src/features/overview/composite/TimeElements.tsx, apps/server/src/stores/__tests__/runtimeState.test.ts, apps/server/src/stores/runtimeState.ts, e2e/tests/features/213-arrange-while-playing.spec.ts
this PR fixes the issue where the data for expected start of the flag event was not cleared when said event was un-flagged by the user
=> Fix: still counting to un-flaged event

apps/server/src/api-data/db/db.controller.ts, apps/server/src/utils/upload.ts
this is an attempt at fixing the user issue with the unescaped characters
The user seemed to have gotten a file named `'MemoriaÃ'$'\302\205'' Kamili Skolimowskiej 2025.json'` which broke the load
It turned out that our quick project and upload routes did not sanitise the file name. I was unable to find any other routes where the sanitation did not happen
=> fix: ensure filename sanitation in all routes

apps/client/src/views/cuesheet/cuesheet-table/cuesheet-table-elements/rowObserver.ts
The IntersectionObserver callback in rowObserver.ts was capturing the `addVisibleRow` and `removeVisibleRow` actions from the Zustand store only once, at the time of the observer's creation.
This created a potential for a stale closure bug, where the observer would call outdated action functions if the store's state or actions were ever re-initialized. This would lead to the application's state not being updated correctly, causing the bug where visible rows would not render their content.
This commit fixes the issue by calling `useVisibleRowsStore.getState()` inside the observer callback. This ensures that the latest, freshest versions of the action functions are always used, preventing the stale state bug.
=> fix(client): use fresh state in row observer to prevent stale closures

apps/server/src/api-data/rundown/rundown.service.ts
fixes the edge case were grouping the running event would not update group metadata
=> fix: notify runtimeStore of events bieng groupd

apps/client/src/features/rundown/Rundown.tsx, apps/client/src/features/rundown/rundown-event/RundownEvent.tsx, apps/client/src/features/rundown/rundown-group/RundownGroup.tsx, apps/client/src/features/rundown/rundown.utils.ts
Fixes two issues related to reordering:
- reordering groups would cause groups to be inserted one inside the other
- previous logic allowed groups to be added at the top of a group
=> fix: prevent dropping a group inside another

apps/client/src/views/common/schedule/ScheduleItem.tsx, apps/server/src/stores/runtimeState.ts
fixes an issue where we would not set epoch and daystart when starting in roll, which prevented us from calculating offsets
=> refactor: set start metadata when starting from roll

.github/workflows/build.yml, .github/workflows/build_cli.yml, .github/workflows/build_resolver.yml, .github/workflows/test.yml, pnpm-workspace.yaml
- set `useNodeVersion` in `pnpm-workspace.yaml` 
- change GitHub actions to rely pnpm setting up node with that specified version
=> set pnpm `useNodeVersion` property to drive node version in GitHub workflows
